package co.com.tactusoft.medical.model.entities;

// Generated 19/03/2012 05:54:55 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MedBodyDetail generated by hbm2java
 */
@Entity
@Table(name = "med_body_detail", catalog = "medical_db")
public class MedBodyDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private MedBody medBody;
	private String title;
	private String url;
	private String gender;
	private int state;

	public MedBodyDetail() {
	}

	public MedBodyDetail(BigDecimal id, MedBody medBody, String title,
			String url, String gender, int state) {
		this.id = id;
		this.medBody = medBody;
		this.title = title;
		this.url = url;
		this.gender = gender;
		this.state = state;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_body", nullable = false)
	public MedBody getMedBody() {
		return this.medBody;
	}

	public void setMedBody(MedBody medBody) {
		this.medBody = medBody;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url", nullable = false, length = 4000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
