package co.com.tactusoft.medical.model.entities;

// Generated 15/03/2012 05:47:01 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MedCombination generated by hbm2java
 */
@Entity
@Table(name = "med_combination", catalog = "medical_db")
public class MedCombination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private Integer idGroup;
	private MedQuestion medQuestion;
	private MedAnswer medAnswer;

	public MedCombination() {
	}

	public MedCombination(BigDecimal id, Integer idGroup,
			MedQuestion medQuestion, MedAnswer medAnswer) {
		this.id = id;
		this.idGroup = idGroup;
		this.medQuestion = medQuestion;
		this.medAnswer = medAnswer;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_group", nullable = false)
	public Integer getIdGroup() {
		return idGroup;
	}

	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_question", nullable = false)
	public MedQuestion getMedQuestion() {
		return this.medQuestion;
	}

	public void setMedQuestion(MedQuestion medQuestion) {
		this.medQuestion = medQuestion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_answer", nullable = false)
	public MedAnswer getMedAnswer() {
		return this.medAnswer;
	}

	public void setMedAnswer(MedAnswer medAnswer) {
		this.medAnswer = medAnswer;
	}

}
