package co.com.tactusoft.medical.model.entities;

// Generated 5/03/2012 02:36:02 PM by Hibernate Tools 3.4.0.CR1

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 * MedTopic generated by hbm2java
 */
@Entity
@Table(name = "med_topic", catalog = "medical_db")
public class MedTopic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private byte[] image;
	private int state;
	private int numVersion;
	private Set<MedQuestion> medQuestions = new HashSet<MedQuestion>(0);

	public MedTopic() {
	}

	public MedTopic(BigDecimal id, String name, int state, int numVersion) {
		this.id = id;
		this.name = name;
		this.state = state;
		this.numVersion = numVersion;
	}

	public MedTopic(BigDecimal id, String name, byte[] image, int state,
			int numVersion, Set<MedQuestion> medQuestions) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.state = state;
		this.numVersion = numVersion;
		this.medQuestions = medQuestions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "num_version", nullable = false)
	public int getNumVersion() {
		return this.numVersion;
	}

	public void setNumVersion(int numVersion) {
		this.numVersion = numVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medTopic")
	public Set<MedQuestion> getMedQuestions() {
		return this.medQuestions;
	}

	public void setMedQuestions(Set<MedQuestion> medQuestions) {
		this.medQuestions = medQuestions;
	}

	@Transient
	public StreamedContent getCurrentImage() {
		InputStream in = new ByteArrayInputStream(this.getImage());
		StreamedContent image = new DefaultStreamedContent(in);
		return image;
	}

}
