package co.com.tactusoft.video.model.entities;

// Generated 15/03/2012 04:01:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MedCombination generated by hbm2java
 */
@Entity
@Table(name = "vid_combination", catalog = "medical_video_db")
public class VidCombination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private VidQuestion medQuestionByIdQuestion;
	private VidQuestion medQuestionByNextQuestion;
	private String answers;

	public VidCombination() {
	}

	public VidCombination(BigDecimal id, VidQuestion medQuestionByIdQuestion,
			VidQuestion medQuestionByNextQuestion, String answers) {
		this.id = id;
		this.medQuestionByIdQuestion = medQuestionByIdQuestion;
		this.medQuestionByNextQuestion = medQuestionByNextQuestion;
		this.answers = answers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_question", nullable = false)
	public VidQuestion getMedQuestionByIdQuestion() {
		return this.medQuestionByIdQuestion;
	}

	public void setMedQuestionByIdQuestion(VidQuestion medQuestionByIdQuestion) {
		this.medQuestionByIdQuestion = medQuestionByIdQuestion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "next_question", nullable = false)
	public VidQuestion getMedQuestionByNextQuestion() {
		return this.medQuestionByNextQuestion;
	}

	public void setMedQuestionByNextQuestion(
			VidQuestion medQuestionByNextQuestion) {
		this.medQuestionByNextQuestion = medQuestionByNextQuestion;
	}

	@Column(name = "answers", nullable = false)
	public String getAnswers() {
		return this.answers;
	}

	public void setAnswers(String answers) {
		this.answers = answers;
	}

}
