package co.com.tactusoft.video.model.entities;

// Generated 5/04/2012 10:45:54 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VidTopic generated by hbm2java
 */
@Entity
@Table(name = "vid_topic", catalog = "medical_video_db")
public class VidTopic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private String image;
	private String gender;
	private int state;
	private Set<VidUserTopic> vidUserTopics = new HashSet<VidUserTopic>(0);
	private Set<VidPackageTopic> vidPackageTopics = new HashSet<VidPackageTopic>(
			0);
	private Set<VidQuestion> vidQuestions = new HashSet<VidQuestion>(0);

	public VidTopic() {
	}

	public VidTopic(BigDecimal id, String name, String gender, int state) {
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.state = state;
	}

	public VidTopic(BigDecimal id, String name, String image, String gender,
			int state, Set<VidUserTopic> vidUserTopics,
			Set<VidPackageTopic> vidPackageTopics, Set<VidQuestion> vidQuestions) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.gender = gender;
		this.state = state;
		this.vidUserTopics = vidUserTopics;
		this.vidPackageTopics = vidPackageTopics;
		this.vidQuestions = vidQuestions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidTopic")
	public Set<VidUserTopic> getVidUserTopics() {
		return this.vidUserTopics;
	}

	public void setVidUserTopics(Set<VidUserTopic> vidUserTopics) {
		this.vidUserTopics = vidUserTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidTopic")
	public Set<VidPackageTopic> getVidPackageTopics() {
		return this.vidPackageTopics;
	}

	public void setVidPackageTopics(Set<VidPackageTopic> vidPackageTopics) {
		this.vidPackageTopics = vidPackageTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidTopic")
	public Set<VidQuestion> getVidQuestions() {
		return this.vidQuestions;
	}

	public void setVidQuestions(Set<VidQuestion> vidQuestions) {
		this.vidQuestions = vidQuestions;
	}

}
