package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmConsent generated by hbm2java
 */
@Entity
@Table(name = "crm_consent", catalog = "crm_db")
public class CrmConsent implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private CrmPatient crmPatient;
	private Date dateInformed;
	private byte[] consentFile;

	public CrmConsent() {
	}

	public CrmConsent(CrmPatient crmPatient, Date dateInformed,
			byte[] consentFile) {
		this.crmPatient = crmPatient;
		this.dateInformed = dateInformed;
		this.consentFile = consentFile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_informed", nullable = false, length = 19)
	public Date getDateInformed() {
		return this.dateInformed;
	}

	public void setDateInformed(Date dateInformed) {
		this.dateInformed = dateInformed;
	}

	@Column(name = "consent_file", nullable = false)
	public byte[] getConsentFile() {
		return this.consentFile;
	}

	public void setConsentFile(byte[] consentFile) {
		this.consentFile = consentFile;
	}

}
