package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CrmCampaignDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign_detail", catalog = "crm_db")
public class CrmCampaignDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmCampaign crmCampaign;
	private CrmAppointment crmAppointment;
	private String codMaterial;
	private String descMaterial;
	private Integer days;
	private String campaingType;

	public CrmCampaignDetail() {
	}

	public CrmCampaignDetail(BigDecimal id, CrmCampaign crmCampaign) {
		this.id = id;
		this.crmCampaign = crmCampaign;
	}

	public CrmCampaignDetail(BigDecimal id, CrmCampaign crmCampaign,
			CrmAppointment crmAppointment, String codMaterial,
			String descMaterial, Integer days, String campaingType) {
		this.id = id;
		this.crmCampaign = crmCampaign;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
		this.crmAppointment = crmAppointment;
		this.days = days;
		this.campaingType = campaingType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_campaign", nullable = false)
	public CrmCampaign getCrmCampaign() {
		return this.crmCampaign;
	}

	public void setCrmCampaign(CrmCampaign crmCampaign) {
		this.crmCampaign = crmCampaign;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "cod_material", length = 18)
	public String getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(String codMaterial) {
		this.codMaterial = codMaterial;
	}

	@Column(name = "desc_material", length = 1000)
	public String getDescMaterial() {
		return this.descMaterial;
	}

	public void setDescMaterial(String descMaterial) {
		this.descMaterial = descMaterial;
	}

	@Column(name = "days")
	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	@Column(name = "campaing_type", length = 30)
	public String getCampaingType() {
		return this.campaingType;
	}

	public void setCampaingType(String campaingType) {
		this.campaingType = campaingType;
	}

	@Transient
	public String getDescCampaingType() {
		return this.getCampaingType().equals("NO_ATTENDET") ? "No asistió a la cita"
				: this.getCampaingType().equals("CONFIRMED") ? "Confirmar la cita"
						: "No ha asistido a control en 25 días";
	}

}
