package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyOdontogram generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_odontogram", catalog = "crm_db")
public class CrmOdontologyOdontogram implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Byte tooth18;
	private Byte tooth17;
	private Byte tooth16;
	private Byte tooth15;
	private Byte tooth14;
	private Byte tooth13;
	private Byte tooth12;
	private Byte tooth11;
	private Byte tooth21;
	private Byte tooth22;
	private Byte tooth23;
	private Byte tooth24;
	private Byte tooth25;
	private Byte tooth26;
	private Byte tooth27;
	private Byte tooth28;
	private Byte tooth55;
	private Byte tooth54;
	private Byte tooth53;
	private Byte tooth52;
	private Byte tooth51;
	private Byte tooth61;
	private Byte tooth62;
	private Byte tooth63;
	private Byte tooth64;
	private Byte tooth65;
	private Byte tooth85;
	private Byte tooth84;
	private Byte tooth83;
	private Byte tooth82;
	private Byte tooth81;
	private Byte tooth71;
	private Byte tooth72;
	private Byte tooth73;
	private Byte tooth74;
	private Byte tooth75;
	private Byte tooth48;
	private Byte tooth47;
	private Byte tooth46;
	private Byte tooth45;
	private Byte tooth44;
	private Byte tooth43;
	private Byte tooth42;
	private Byte tooth41;
	private Byte tooth31;
	private Byte tooth32;
	private Byte tooth33;
	private Byte tooth34;
	private Byte tooth35;
	private Byte tooth36;
	private Byte tooth37;
	private Byte tooth38;

	public CrmOdontologyOdontogram() {
	}

	public CrmOdontologyOdontogram(CrmAppointment crmAppointment, Byte tooth18,
			Byte tooth17, Byte tooth16, Byte tooth15, Byte tooth14,
			Byte tooth13, Byte tooth12, Byte tooth11, Byte tooth21,
			Byte tooth22, Byte tooth23, Byte tooth24, Byte tooth25,
			Byte tooth26, Byte tooth27, Byte tooth28, Byte tooth55,
			Byte tooth54, Byte tooth53, Byte tooth52, Byte tooth51,
			Byte tooth61, Byte tooth62, Byte tooth63, Byte tooth64,
			Byte tooth65, Byte tooth85, Byte tooth84, Byte tooth83,
			Byte tooth82, Byte tooth81, Byte tooth71, Byte tooth72,
			Byte tooth73, Byte tooth74, Byte tooth75, Byte tooth48,
			Byte tooth47, Byte tooth46, Byte tooth45, Byte tooth44,
			Byte tooth43, Byte tooth42, Byte tooth41, Byte tooth31,
			Byte tooth32, Byte tooth33, Byte tooth34, Byte tooth35,
			Byte tooth36, Byte tooth37, Byte tooth38) {
		this.crmAppointment = crmAppointment;
		this.tooth18 = tooth18;
		this.tooth17 = tooth17;
		this.tooth16 = tooth16;
		this.tooth15 = tooth15;
		this.tooth14 = tooth14;
		this.tooth13 = tooth13;
		this.tooth12 = tooth12;
		this.tooth11 = tooth11;
		this.tooth21 = tooth21;
		this.tooth22 = tooth22;
		this.tooth23 = tooth23;
		this.tooth24 = tooth24;
		this.tooth25 = tooth25;
		this.tooth26 = tooth26;
		this.tooth27 = tooth27;
		this.tooth28 = tooth28;
		this.tooth55 = tooth55;
		this.tooth54 = tooth54;
		this.tooth53 = tooth53;
		this.tooth52 = tooth52;
		this.tooth51 = tooth51;
		this.tooth61 = tooth61;
		this.tooth62 = tooth62;
		this.tooth63 = tooth63;
		this.tooth64 = tooth64;
		this.tooth65 = tooth65;
		this.tooth85 = tooth85;
		this.tooth84 = tooth84;
		this.tooth83 = tooth83;
		this.tooth82 = tooth82;
		this.tooth81 = tooth81;
		this.tooth71 = tooth71;
		this.tooth72 = tooth72;
		this.tooth73 = tooth73;
		this.tooth74 = tooth74;
		this.tooth75 = tooth75;
		this.tooth48 = tooth48;
		this.tooth47 = tooth47;
		this.tooth46 = tooth46;
		this.tooth45 = tooth45;
		this.tooth44 = tooth44;
		this.tooth43 = tooth43;
		this.tooth42 = tooth42;
		this.tooth41 = tooth41;
		this.tooth31 = tooth31;
		this.tooth32 = tooth32;
		this.tooth33 = tooth33;
		this.tooth34 = tooth34;
		this.tooth35 = tooth35;
		this.tooth36 = tooth36;
		this.tooth37 = tooth37;
		this.tooth38 = tooth38;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment")
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "tooth_18")
	public Byte getTooth18() {
		return this.tooth18;
	}

	public void setTooth18(Byte tooth18) {
		this.tooth18 = tooth18;
	}

	@Column(name = "tooth_17")
	public Byte getTooth17() {
		return this.tooth17;
	}

	public void setTooth17(Byte tooth17) {
		this.tooth17 = tooth17;
	}

	@Column(name = "tooth_16")
	public Byte getTooth16() {
		return this.tooth16;
	}

	public void setTooth16(Byte tooth16) {
		this.tooth16 = tooth16;
	}

	@Column(name = "tooth_15")
	public Byte getTooth15() {
		return this.tooth15;
	}

	public void setTooth15(Byte tooth15) {
		this.tooth15 = tooth15;
	}

	@Column(name = "tooth_14")
	public Byte getTooth14() {
		return this.tooth14;
	}

	public void setTooth14(Byte tooth14) {
		this.tooth14 = tooth14;
	}

	@Column(name = "tooth_13")
	public Byte getTooth13() {
		return this.tooth13;
	}

	public void setTooth13(Byte tooth13) {
		this.tooth13 = tooth13;
	}

	@Column(name = "tooth_12")
	public Byte getTooth12() {
		return this.tooth12;
	}

	public void setTooth12(Byte tooth12) {
		this.tooth12 = tooth12;
	}

	@Column(name = "tooth_11")
	public Byte getTooth11() {
		return this.tooth11;
	}

	public void setTooth11(Byte tooth11) {
		this.tooth11 = tooth11;
	}

	@Column(name = "tooth_21")
	public Byte getTooth21() {
		return this.tooth21;
	}

	public void setTooth21(Byte tooth21) {
		this.tooth21 = tooth21;
	}

	@Column(name = "tooth_22")
	public Byte getTooth22() {
		return this.tooth22;
	}

	public void setTooth22(Byte tooth22) {
		this.tooth22 = tooth22;
	}

	@Column(name = "tooth_23")
	public Byte getTooth23() {
		return this.tooth23;
	}

	public void setTooth23(Byte tooth23) {
		this.tooth23 = tooth23;
	}

	@Column(name = "tooth_24")
	public Byte getTooth24() {
		return this.tooth24;
	}

	public void setTooth24(Byte tooth24) {
		this.tooth24 = tooth24;
	}

	@Column(name = "tooth_25")
	public Byte getTooth25() {
		return this.tooth25;
	}

	public void setTooth25(Byte tooth25) {
		this.tooth25 = tooth25;
	}

	@Column(name = "tooth_26")
	public Byte getTooth26() {
		return this.tooth26;
	}

	public void setTooth26(Byte tooth26) {
		this.tooth26 = tooth26;
	}

	@Column(name = "tooth_27")
	public Byte getTooth27() {
		return this.tooth27;
	}

	public void setTooth27(Byte tooth27) {
		this.tooth27 = tooth27;
	}

	@Column(name = "tooth_28")
	public Byte getTooth28() {
		return this.tooth28;
	}

	public void setTooth28(Byte tooth28) {
		this.tooth28 = tooth28;
	}

	@Column(name = "tooth_55")
	public Byte getTooth55() {
		return this.tooth55;
	}

	public void setTooth55(Byte tooth55) {
		this.tooth55 = tooth55;
	}

	@Column(name = "tooth_54")
	public Byte getTooth54() {
		return this.tooth54;
	}

	public void setTooth54(Byte tooth54) {
		this.tooth54 = tooth54;
	}

	@Column(name = "tooth_53")
	public Byte getTooth53() {
		return this.tooth53;
	}

	public void setTooth53(Byte tooth53) {
		this.tooth53 = tooth53;
	}

	@Column(name = "tooth_52")
	public Byte getTooth52() {
		return this.tooth52;
	}

	public void setTooth52(Byte tooth52) {
		this.tooth52 = tooth52;
	}

	@Column(name = "tooth_51")
	public Byte getTooth51() {
		return this.tooth51;
	}

	public void setTooth51(Byte tooth51) {
		this.tooth51 = tooth51;
	}

	@Column(name = "tooth_61")
	public Byte getTooth61() {
		return this.tooth61;
	}

	public void setTooth61(Byte tooth61) {
		this.tooth61 = tooth61;
	}

	@Column(name = "tooth_62")
	public Byte getTooth62() {
		return this.tooth62;
	}

	public void setTooth62(Byte tooth62) {
		this.tooth62 = tooth62;
	}

	@Column(name = "tooth_63")
	public Byte getTooth63() {
		return this.tooth63;
	}

	public void setTooth63(Byte tooth63) {
		this.tooth63 = tooth63;
	}

	@Column(name = "tooth_64")
	public Byte getTooth64() {
		return this.tooth64;
	}

	public void setTooth64(Byte tooth64) {
		this.tooth64 = tooth64;
	}

	@Column(name = "tooth_65")
	public Byte getTooth65() {
		return this.tooth65;
	}

	public void setTooth65(Byte tooth65) {
		this.tooth65 = tooth65;
	}

	@Column(name = "tooth_85")
	public Byte getTooth85() {
		return this.tooth85;
	}

	public void setTooth85(Byte tooth85) {
		this.tooth85 = tooth85;
	}

	@Column(name = "tooth_84")
	public Byte getTooth84() {
		return this.tooth84;
	}

	public void setTooth84(Byte tooth84) {
		this.tooth84 = tooth84;
	}

	@Column(name = "tooth_83")
	public Byte getTooth83() {
		return this.tooth83;
	}

	public void setTooth83(Byte tooth83) {
		this.tooth83 = tooth83;
	}

	@Column(name = "tooth_82")
	public Byte getTooth82() {
		return this.tooth82;
	}

	public void setTooth82(Byte tooth82) {
		this.tooth82 = tooth82;
	}

	@Column(name = "tooth_81")
	public Byte getTooth81() {
		return this.tooth81;
	}

	public void setTooth81(Byte tooth81) {
		this.tooth81 = tooth81;
	}

	@Column(name = "tooth_71")
	public Byte getTooth71() {
		return this.tooth71;
	}

	public void setTooth71(Byte tooth71) {
		this.tooth71 = tooth71;
	}

	@Column(name = "tooth_72")
	public Byte getTooth72() {
		return this.tooth72;
	}

	public void setTooth72(Byte tooth72) {
		this.tooth72 = tooth72;
	}

	@Column(name = "tooth_73")
	public Byte getTooth73() {
		return this.tooth73;
	}

	public void setTooth73(Byte tooth73) {
		this.tooth73 = tooth73;
	}

	@Column(name = "tooth_74")
	public Byte getTooth74() {
		return this.tooth74;
	}

	public void setTooth74(Byte tooth74) {
		this.tooth74 = tooth74;
	}

	@Column(name = "tooth_75")
	public Byte getTooth75() {
		return this.tooth75;
	}

	public void setTooth75(Byte tooth75) {
		this.tooth75 = tooth75;
	}

	@Column(name = "tooth_48")
	public Byte getTooth48() {
		return this.tooth48;
	}

	public void setTooth48(Byte tooth48) {
		this.tooth48 = tooth48;
	}

	@Column(name = "tooth_47")
	public Byte getTooth47() {
		return this.tooth47;
	}

	public void setTooth47(Byte tooth47) {
		this.tooth47 = tooth47;
	}

	@Column(name = "tooth_46")
	public Byte getTooth46() {
		return this.tooth46;
	}

	public void setTooth46(Byte tooth46) {
		this.tooth46 = tooth46;
	}

	@Column(name = "tooth_45")
	public Byte getTooth45() {
		return this.tooth45;
	}

	public void setTooth45(Byte tooth45) {
		this.tooth45 = tooth45;
	}

	@Column(name = "tooth_44")
	public Byte getTooth44() {
		return this.tooth44;
	}

	public void setTooth44(Byte tooth44) {
		this.tooth44 = tooth44;
	}

	@Column(name = "tooth_43")
	public Byte getTooth43() {
		return this.tooth43;
	}

	public void setTooth43(Byte tooth43) {
		this.tooth43 = tooth43;
	}

	@Column(name = "tooth_42")
	public Byte getTooth42() {
		return this.tooth42;
	}

	public void setTooth42(Byte tooth42) {
		this.tooth42 = tooth42;
	}

	@Column(name = "tooth_41")
	public Byte getTooth41() {
		return this.tooth41;
	}

	public void setTooth41(Byte tooth41) {
		this.tooth41 = tooth41;
	}

	@Column(name = "tooth_31")
	public Byte getTooth31() {
		return this.tooth31;
	}

	public void setTooth31(Byte tooth31) {
		this.tooth31 = tooth31;
	}

	@Column(name = "tooth_32")
	public Byte getTooth32() {
		return this.tooth32;
	}

	public void setTooth32(Byte tooth32) {
		this.tooth32 = tooth32;
	}

	@Column(name = "tooth_33")
	public Byte getTooth33() {
		return this.tooth33;
	}

	public void setTooth33(Byte tooth33) {
		this.tooth33 = tooth33;
	}

	@Column(name = "tooth_34")
	public Byte getTooth34() {
		return this.tooth34;
	}

	public void setTooth34(Byte tooth34) {
		this.tooth34 = tooth34;
	}

	@Column(name = "tooth_35")
	public Byte getTooth35() {
		return this.tooth35;
	}

	public void setTooth35(Byte tooth35) {
		this.tooth35 = tooth35;
	}

	@Column(name = "tooth_36")
	public Byte getTooth36() {
		return this.tooth36;
	}

	public void setTooth36(Byte tooth36) {
		this.tooth36 = tooth36;
	}

	@Column(name = "tooth_37")
	public Byte getTooth37() {
		return this.tooth37;
	}

	public void setTooth37(Byte tooth37) {
		this.tooth37 = tooth37;
	}

	@Column(name = "tooth_38")
	public Byte getTooth38() {
		return this.tooth38;
	}

	public void setTooth38(Byte tooth38) {
		this.tooth38 = tooth38;
	}

}
