package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyPersonalRecord generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_personal_record", catalog = "crm_db")
public class CrmOdontologyPersonalRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Integer medicalTreatment;
	private Integer medicine;
	private Integer surgery;
	private Integer bloodTransfusion;
	private Integer bloodPressureHigh;
	private Integer bloodPressureLow;
	private Integer penicillinAllergy;
	private Integer anesthesiaAllergy;
	private Integer aspirinAllergy;
	private String otherAllergy;
	private Integer excesivesBlood;
	private Integer bloodProblem;
	private Integer anemiaLeukemiaHemophilia;
	private Integer hiv;
	private Integer retroviral;
	private Integer pregnant;
	private Integer contraceptives;
	private Integer venereaslDiseases;
	private Integer heartProblems;
	private Integer hepatitis;
	private Integer asthma;
	private Integer rheumaticFever;
	private Integer diabetes;
	private Integer grasticUlcer;
	private Integer thyroid;
	private Integer limitationOpenCloseMouth;
	private Integer noiseJawOpenCloseMouth;
	private Integer herpesThrush;
	private Integer bitLipsNailsHabit;
	private Integer smokeHabit;
	private Integer cigarettesDayHabit;
	private Integer citrusFoodsHabit;
	private Integer bitObjectsHabit;
	private Integer toothClenchHabit;
	private Integer mouthBreathHabit;
	private String obs;

	public CrmOdontologyPersonalRecord() {
	}

	public CrmOdontologyPersonalRecord(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyPersonalRecord(CrmAppointment crmAppointment,
			Integer medicalTreatment, Integer medicine, Integer surgery,
			Integer bloodTransfusion, Integer bloodPressureHigh,
			Integer bloodPressureLow, Integer penicillinAllergy,
			Integer anesthesiaAllergy, Integer aspirinAllergy,
			String otherAllergy, Integer excesivesBlood, Integer bloodProblem,
			Integer anemiaLeukemiaHemophilia, Integer hiv, Integer retroviral,
			Integer pregnant, Integer contraceptives,
			Integer venereaslDiseases, Integer heartProblems,
			Integer hepatitis, Integer asthma, Integer rheumaticFever,
			Integer diabetes, Integer grasticUlcer, Integer thyroid,
			Integer limitationOpenCloseMouth, Integer noiseJawOpenCloseMouth,
			Integer herpesThrush, Integer bitLipsNailsHabit,
			Integer smokeHabit, Integer cigarettesDayHabit,
			Integer citrusFoodsHabit, Integer bitObjectsHabit,
			Integer toothClenchHabit, Integer mouthBreathHabit, String obs) {
		this.crmAppointment = crmAppointment;
		this.medicalTreatment = medicalTreatment;
		this.medicine = medicine;
		this.surgery = surgery;
		this.bloodTransfusion = bloodTransfusion;
		this.bloodPressureHigh = bloodPressureHigh;
		this.bloodPressureLow = bloodPressureLow;
		this.penicillinAllergy = penicillinAllergy;
		this.anesthesiaAllergy = anesthesiaAllergy;
		this.aspirinAllergy = aspirinAllergy;
		this.otherAllergy = otherAllergy;
		this.excesivesBlood = excesivesBlood;
		this.bloodProblem = bloodProblem;
		this.anemiaLeukemiaHemophilia = anemiaLeukemiaHemophilia;
		this.hiv = hiv;
		this.retroviral = retroviral;
		this.pregnant = pregnant;
		this.contraceptives = contraceptives;
		this.venereaslDiseases = venereaslDiseases;
		this.heartProblems = heartProblems;
		this.hepatitis = hepatitis;
		this.asthma = asthma;
		this.rheumaticFever = rheumaticFever;
		this.diabetes = diabetes;
		this.grasticUlcer = grasticUlcer;
		this.thyroid = thyroid;
		this.limitationOpenCloseMouth = limitationOpenCloseMouth;
		this.noiseJawOpenCloseMouth = noiseJawOpenCloseMouth;
		this.herpesThrush = herpesThrush;
		this.bitLipsNailsHabit = bitLipsNailsHabit;
		this.smokeHabit = smokeHabit;
		this.cigarettesDayHabit = cigarettesDayHabit;
		this.citrusFoodsHabit = citrusFoodsHabit;
		this.bitObjectsHabit = bitObjectsHabit;
		this.toothClenchHabit = toothClenchHabit;
		this.mouthBreathHabit = mouthBreathHabit;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "medical_treatment")
	public Integer getMedicalTreatment() {
		return this.medicalTreatment;
	}

	public void setMedicalTreatment(Integer medicalTreatment) {
		this.medicalTreatment = medicalTreatment;
	}

	@Column(name = "medicine")
	public Integer getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Integer medicine) {
		this.medicine = medicine;
	}

	@Column(name = "surgery")
	public Integer getSurgery() {
		return this.surgery;
	}

	public void setSurgery(Integer surgery) {
		this.surgery = surgery;
	}

	@Column(name = "blood_transfusion")
	public Integer getBloodTransfusion() {
		return this.bloodTransfusion;
	}

	public void setBloodTransfusion(Integer bloodTransfusion) {
		this.bloodTransfusion = bloodTransfusion;
	}

	@Column(name = "blood_pressure_high")
	public Integer getBloodPressureHigh() {
		return this.bloodPressureHigh;
	}

	public void setBloodPressureHigh(Integer bloodPressureHigh) {
		this.bloodPressureHigh = bloodPressureHigh;
	}

	@Column(name = "blood_pressure_low")
	public Integer getBloodPressureLow() {
		return this.bloodPressureLow;
	}

	public void setBloodPressureLow(Integer bloodPressureLow) {
		this.bloodPressureLow = bloodPressureLow;
	}

	@Column(name = "penicillin_allergy")
	public Integer getPenicillinAllergy() {
		return this.penicillinAllergy;
	}

	public void setPenicillinAllergy(Integer penicillinAllergy) {
		this.penicillinAllergy = penicillinAllergy;
	}

	@Column(name = "anesthesia_allergy")
	public Integer getAnesthesiaAllergy() {
		return this.anesthesiaAllergy;
	}

	public void setAnesthesiaAllergy(Integer anesthesiaAllergy) {
		this.anesthesiaAllergy = anesthesiaAllergy;
	}

	@Column(name = "aspirin_allergy")
	public Integer getAspirinAllergy() {
		return this.aspirinAllergy;
	}

	public void setAspirinAllergy(Integer aspirinAllergy) {
		this.aspirinAllergy = aspirinAllergy;
	}

	@Column(name = "other_allergy", length = 65535)
	public String getOtherAllergy() {
		return this.otherAllergy;
	}

	public void setOtherAllergy(String otherAllergy) {
		this.otherAllergy = otherAllergy;
	}

	@Column(name = "excesives_blood")
	public Integer getExcesivesBlood() {
		return this.excesivesBlood;
	}

	public void setExcesivesBlood(Integer excesivesBlood) {
		this.excesivesBlood = excesivesBlood;
	}

	@Column(name = "blood_problem")
	public Integer getBloodProblem() {
		return this.bloodProblem;
	}

	public void setBloodProblem(Integer bloodProblem) {
		this.bloodProblem = bloodProblem;
	}

	@Column(name = "anemia_leukemia_hemophilia")
	public Integer getAnemiaLeukemiaHemophilia() {
		return this.anemiaLeukemiaHemophilia;
	}

	public void setAnemiaLeukemiaHemophilia(Integer anemiaLeukemiaHemophilia) {
		this.anemiaLeukemiaHemophilia = anemiaLeukemiaHemophilia;
	}

	@Column(name = "hiv")
	public Integer getHiv() {
		return this.hiv;
	}

	public void setHiv(Integer hiv) {
		this.hiv = hiv;
	}

	@Column(name = "retroviral")
	public Integer getRetroviral() {
		return this.retroviral;
	}

	public void setRetroviral(Integer retroviral) {
		this.retroviral = retroviral;
	}

	@Column(name = "pregnant")
	public Integer getPregnant() {
		return this.pregnant;
	}

	public void setPregnant(Integer pregnant) {
		this.pregnant = pregnant;
	}

	@Column(name = "contraceptives")
	public Integer getContraceptives() {
		return this.contraceptives;
	}

	public void setContraceptives(Integer contraceptives) {
		this.contraceptives = contraceptives;
	}

	@Column(name = "venereasl_diseases")
	public Integer getVenereaslDiseases() {
		return this.venereaslDiseases;
	}

	public void setVenereaslDiseases(Integer venereaslDiseases) {
		this.venereaslDiseases = venereaslDiseases;
	}

	@Column(name = "heart_problems")
	public Integer getHeartProblems() {
		return this.heartProblems;
	}

	public void setHeartProblems(Integer heartProblems) {
		this.heartProblems = heartProblems;
	}

	@Column(name = "hepatitis")
	public Integer getHepatitis() {
		return this.hepatitis;
	}

	public void setHepatitis(Integer hepatitis) {
		this.hepatitis = hepatitis;
	}

	@Column(name = "asthma")
	public Integer getAsthma() {
		return this.asthma;
	}

	public void setAsthma(Integer asthma) {
		this.asthma = asthma;
	}

	@Column(name = "rheumatic_fever")
	public Integer getRheumaticFever() {
		return this.rheumaticFever;
	}

	public void setRheumaticFever(Integer rheumaticFever) {
		this.rheumaticFever = rheumaticFever;
	}

	@Column(name = "diabetes")
	public Integer getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(Integer diabetes) {
		this.diabetes = diabetes;
	}

	@Column(name = "grastic_ulcer")
	public Integer getGrasticUlcer() {
		return this.grasticUlcer;
	}

	public void setGrasticUlcer(Integer grasticUlcer) {
		this.grasticUlcer = grasticUlcer;
	}

	@Column(name = "thyroid")
	public Integer getThyroid() {
		return this.thyroid;
	}

	public void setThyroid(Integer thyroid) {
		this.thyroid = thyroid;
	}

	@Column(name = "limitation_open_close_mouth")
	public Integer getLimitationOpenCloseMouth() {
		return this.limitationOpenCloseMouth;
	}

	public void setLimitationOpenCloseMouth(Integer limitationOpenCloseMouth) {
		this.limitationOpenCloseMouth = limitationOpenCloseMouth;
	}

	@Column(name = "noise_jaw_open_close_mouth")
	public Integer getNoiseJawOpenCloseMouth() {
		return this.noiseJawOpenCloseMouth;
	}

	public void setNoiseJawOpenCloseMouth(Integer noiseJawOpenCloseMouth) {
		this.noiseJawOpenCloseMouth = noiseJawOpenCloseMouth;
	}

	@Column(name = "herpes_thrush")
	public Integer getHerpesThrush() {
		return this.herpesThrush;
	}

	public void setHerpesThrush(Integer herpesThrush) {
		this.herpesThrush = herpesThrush;
	}

	@Column(name = "bit_lips_nails_habit")
	public Integer getBitLipsNailsHabit() {
		return this.bitLipsNailsHabit;
	}

	public void setBitLipsNailsHabit(Integer bitLipsNailsHabit) {
		this.bitLipsNailsHabit = bitLipsNailsHabit;
	}

	@Column(name = "smoke_habit")
	public Integer getSmokeHabit() {
		return this.smokeHabit;
	}

	public void setSmokeHabit(Integer smokeHabit) {
		this.smokeHabit = smokeHabit;
	}

	@Column(name = "cigarettes_day_habit")
	public Integer getCigarettesDayHabit() {
		return this.cigarettesDayHabit;
	}

	public void setCigarettesDayHabit(Integer cigarettesDayHabit) {
		this.cigarettesDayHabit = cigarettesDayHabit;
	}

	@Column(name = "citrus_foods_habit")
	public Integer getCitrusFoodsHabit() {
		return this.citrusFoodsHabit;
	}

	public void setCitrusFoodsHabit(Integer citrusFoodsHabit) {
		this.citrusFoodsHabit = citrusFoodsHabit;
	}

	@Column(name = "bit_objects_habit")
	public Integer getBitObjectsHabit() {
		return this.bitObjectsHabit;
	}

	public void setBitObjectsHabit(Integer bitObjectsHabit) {
		this.bitObjectsHabit = bitObjectsHabit;
	}

	@Column(name = "tooth_clench_habit")
	public Integer getToothClenchHabit() {
		return this.toothClenchHabit;
	}

	public void setToothClenchHabit(Integer toothClenchHabit) {
		this.toothClenchHabit = toothClenchHabit;
	}

	@Column(name = "mouth_breath_habit")
	public Integer getMouthBreathHabit() {
		return this.mouthBreathHabit;
	}

	public void setMouthBreathHabit(Integer mouthBreathHabit) {
		this.mouthBreathHabit = mouthBreathHabit;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
