package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologySoftTissue generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_soft_tissue", catalog = "crm_db")
public class CrmOdontologySoftTissue implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Boolean glandNormal;
	private Boolean glandAltered;
	private Boolean lymphNormal;
	private Boolean lymphAltered;
	private Boolean oralMucosaNormal;
	private Boolean oralMucosaAltered;
	private Boolean bracesNormal;
	private Boolean bracesAltered;
	private Boolean tongueNormal;
	private Boolean tongueAltered;
	private Boolean palateNormal;
	private Boolean palateAltered;
	private Boolean mounthFloorNormal;
	private Boolean mounthFloorAltered;
	private Boolean oropharynxNormal;
	private Boolean oropharynxAltered;
	private Boolean tonsilsNormal;
	private Boolean tonsilsAltered;
	private Boolean cheeksNormal;
	private Boolean cheeksAltered;
	private String obs;

	public CrmOdontologySoftTissue() {
	}

	public CrmOdontologySoftTissue(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologySoftTissue(CrmAppointment crmAppointment,
			Boolean glandNormal, Boolean glandAltered, Boolean lymphNormal,
			Boolean lymphAltered, Boolean oralMucosaNormal,
			Boolean oralMucosaAltered, Boolean bracesNormal,
			Boolean bracesAltered, Boolean tongueNormal, Boolean tongueAltered,
			Boolean palateNormal, Boolean palateAltered,
			Boolean mounthFloorNormal, Boolean mounthFloorAltered,
			Boolean oropharynxNormal, Boolean oropharynxAltered,
			Boolean tonsilsNormal, Boolean tonsilsAltered,
			Boolean cheeksNormal, Boolean cheeksAltered, String obs) {
		this.crmAppointment = crmAppointment;
		this.glandNormal = glandNormal;
		this.glandAltered = glandAltered;
		this.lymphNormal = lymphNormal;
		this.lymphAltered = lymphAltered;
		this.oralMucosaNormal = oralMucosaNormal;
		this.oralMucosaAltered = oralMucosaAltered;
		this.bracesNormal = bracesNormal;
		this.bracesAltered = bracesAltered;
		this.tongueNormal = tongueNormal;
		this.tongueAltered = tongueAltered;
		this.palateNormal = palateNormal;
		this.palateAltered = palateAltered;
		this.mounthFloorNormal = mounthFloorNormal;
		this.mounthFloorAltered = mounthFloorAltered;
		this.oropharynxNormal = oropharynxNormal;
		this.oropharynxAltered = oropharynxAltered;
		this.tonsilsNormal = tonsilsNormal;
		this.tonsilsAltered = tonsilsAltered;
		this.cheeksNormal = cheeksNormal;
		this.cheeksAltered = cheeksAltered;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "gland_normal")
	public Boolean getGlandNormal() {
		return this.glandNormal;
	}

	public void setGlandNormal(Boolean glandNormal) {
		this.glandNormal = glandNormal;
	}

	@Column(name = "gland_altered")
	public Boolean getGlandAltered() {
		return this.glandAltered;
	}

	public void setGlandAltered(Boolean glandAltered) {
		this.glandAltered = glandAltered;
	}

	@Column(name = "lymph_normal")
	public Boolean getLymphNormal() {
		return this.lymphNormal;
	}

	public void setLymphNormal(Boolean lymphNormal) {
		this.lymphNormal = lymphNormal;
	}

	@Column(name = "lymph_altered")
	public Boolean getLymphAltered() {
		return this.lymphAltered;
	}

	public void setLymphAltered(Boolean lymphAltered) {
		this.lymphAltered = lymphAltered;
	}

	@Column(name = "oral_mucosa_normal")
	public Boolean getOralMucosaNormal() {
		return this.oralMucosaNormal;
	}

	public void setOralMucosaNormal(Boolean oralMucosaNormal) {
		this.oralMucosaNormal = oralMucosaNormal;
	}

	@Column(name = "oral_mucosa_altered")
	public Boolean getOralMucosaAltered() {
		return this.oralMucosaAltered;
	}

	public void setOralMucosaAltered(Boolean oralMucosaAltered) {
		this.oralMucosaAltered = oralMucosaAltered;
	}

	@Column(name = "braces_normal")
	public Boolean getBracesNormal() {
		return this.bracesNormal;
	}

	public void setBracesNormal(Boolean bracesNormal) {
		this.bracesNormal = bracesNormal;
	}

	@Column(name = "braces_altered")
	public Boolean getBracesAltered() {
		return this.bracesAltered;
	}

	public void setBracesAltered(Boolean bracesAltered) {
		this.bracesAltered = bracesAltered;
	}

	@Column(name = "tongue_normal")
	public Boolean getTongueNormal() {
		return this.tongueNormal;
	}

	public void setTongueNormal(Boolean tongueNormal) {
		this.tongueNormal = tongueNormal;
	}

	@Column(name = "tongue_altered")
	public Boolean getTongueAltered() {
		return this.tongueAltered;
	}

	public void setTongueAltered(Boolean tongueAltered) {
		this.tongueAltered = tongueAltered;
	}

	@Column(name = "palate_normal")
	public Boolean getPalateNormal() {
		return this.palateNormal;
	}

	public void setPalateNormal(Boolean palateNormal) {
		this.palateNormal = palateNormal;
	}

	@Column(name = "palate_altered")
	public Boolean getPalateAltered() {
		return this.palateAltered;
	}

	public void setPalateAltered(Boolean palateAltered) {
		this.palateAltered = palateAltered;
	}

	@Column(name = "mounth_floor_normal")
	public Boolean getMounthFloorNormal() {
		return this.mounthFloorNormal;
	}

	public void setMounthFloorNormal(Boolean mounthFloorNormal) {
		this.mounthFloorNormal = mounthFloorNormal;
	}

	@Column(name = "mounth_floor_altered")
	public Boolean getMounthFloorAltered() {
		return this.mounthFloorAltered;
	}

	public void setMounthFloorAltered(Boolean mounthFloorAltered) {
		this.mounthFloorAltered = mounthFloorAltered;
	}

	@Column(name = "oropharynx_normal")
	public Boolean getOropharynxNormal() {
		return this.oropharynxNormal;
	}

	public void setOropharynxNormal(Boolean oropharynxNormal) {
		this.oropharynxNormal = oropharynxNormal;
	}

	@Column(name = "oropharynx_altered")
	public Boolean getOropharynxAltered() {
		return this.oropharynxAltered;
	}

	public void setOropharynxAltered(Boolean oropharynxAltered) {
		this.oropharynxAltered = oropharynxAltered;
	}

	@Column(name = "tonsils_normal")
	public Boolean getTonsilsNormal() {
		return this.tonsilsNormal;
	}

	public void setTonsilsNormal(Boolean tonsilsNormal) {
		this.tonsilsNormal = tonsilsNormal;
	}

	@Column(name = "tonsils_altered")
	public Boolean getTonsilsAltered() {
		return this.tonsilsAltered;
	}

	public void setTonsilsAltered(Boolean tonsilsAltered) {
		this.tonsilsAltered = tonsilsAltered;
	}

	@Column(name = "cheeks_normal")
	public Boolean getCheeksNormal() {
		return this.cheeksNormal;
	}

	public void setCheeksNormal(Boolean cheeksNormal) {
		this.cheeksNormal = cheeksNormal;
	}

	@Column(name = "cheeks_altered")
	public Boolean getCheeksAltered() {
		return this.cheeksAltered;
	}

	public void setCheeksAltered(Boolean cheeksAltered) {
		this.cheeksAltered = cheeksAltered;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
