package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyPeriodontal generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_periodontal", catalog = "crm_db")
public class CrmOdontologyPeriodontal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Boolean gingivitis;
	private Boolean periodontitis;
	private Boolean mobility;
	private Boolean bagTeeth;
	private Boolean gingivalRecession;
	private Integer plaqueIndex;
	private String observations;

	public CrmOdontologyPeriodontal() {
	}

	public CrmOdontologyPeriodontal(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyPeriodontal(CrmAppointment crmAppointment,
			Boolean gingivitis, Boolean periodontitis, Boolean mobility,
			Boolean bagTeeth, Boolean gingivalRecession, Integer plaqueIndex,
			String observations) {
		this.crmAppointment = crmAppointment;
		this.gingivitis = gingivitis;
		this.periodontitis = periodontitis;
		this.mobility = mobility;
		this.bagTeeth = bagTeeth;
		this.gingivalRecession = gingivalRecession;
		this.plaqueIndex = plaqueIndex;
		this.observations = observations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "gingivitis")
	public Boolean getGingivitis() {
		return this.gingivitis;
	}

	public void setGingivitis(Boolean gingivitis) {
		this.gingivitis = gingivitis;
	}

	@Column(name = "periodontitis")
	public Boolean getPeriodontitis() {
		return this.periodontitis;
	}

	public void setPeriodontitis(Boolean periodontitis) {
		this.periodontitis = periodontitis;
	}

	@Column(name = "mobility")
	public Boolean getMobility() {
		return this.mobility;
	}

	public void setMobility(Boolean mobility) {
		this.mobility = mobility;
	}

	@Column(name = "bag_teeth")
	public Boolean getBagTeeth() {
		return this.bagTeeth;
	}

	public void setBagTeeth(Boolean bagTeeth) {
		this.bagTeeth = bagTeeth;
	}

	@Column(name = "gingival_recession")
	public Boolean getGingivalRecession() {
		return this.gingivalRecession;
	}

	public void setGingivalRecession(Boolean gingivalRecession) {
		this.gingivalRecession = gingivalRecession;
	}

	@Column(name = "plaque_index")
	public Integer getPlaqueIndex() {
		return this.plaqueIndex;
	}

	public void setPlaqueIndex(Integer plaqueIndex) {
		this.plaqueIndex = plaqueIndex;
	}

	@Column(name = "observations", length = 65535)
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

}
