package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyFamilaryRecord generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_familary_record", catalog = "crm_db")
public class CrmOdontologyFamilaryRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private String father;
	private String mother;
	private String sibilings;
	private String grandparents;
	private String obs;

	public CrmOdontologyFamilaryRecord() {
	}

	public CrmOdontologyFamilaryRecord(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyFamilaryRecord(CrmAppointment crmAppointment,
			String father, String mother, String sibilings,
			String grandparents, String obs) {
		this.crmAppointment = crmAppointment;
		this.father = father;
		this.mother = mother;
		this.sibilings = sibilings;
		this.grandparents = grandparents;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "father", length = 65535)
	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	@Column(name = "mother", length = 65535)
	public String getMother() {
		return this.mother;
	}

	public void setMother(String mother) {
		this.mother = mother;
	}

	@Column(name = "sibilings", length = 65535)
	public String getSibilings() {
		return this.sibilings;
	}

	public void setSibilings(String sibilings) {
		this.sibilings = sibilings;
	}

	@Column(name = "grandparents", length = 65535)
	public String getGrandparents() {
		return this.grandparents;
	}

	public void setGrandparents(String grandparents) {
		this.grandparents = grandparents;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
