package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyPersonalRecord generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_personal_record", catalog = "crm_db")
public class CrmOdontologyPersonalRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Boolean medicalTreatment;
	private Boolean medicine;
	private Boolean surgery;
	private Boolean bloodTransfusion;
	private Boolean bloodPressureHigh;
	private Boolean bloodPressureLow;
	private Boolean penicillinAllergy;
	private Boolean anesthesiaAllergy;
	private Boolean aspirinAllergy;
	private String otherAllergy;
	private Boolean excesivesBlood;
	private Boolean bloodProblem;
	private Boolean anemiaLeukemiaHemophilia;
	private Boolean hiv;
	private Boolean retroviral;
	private Boolean pregnant;
	private Boolean contraceptives;
	private Boolean venereaslDiseases;
	private Boolean heartProblems;
	private Boolean hepatitis;
	private Boolean asthma;
	private Boolean rheumaticFever;
	private Boolean diabetes;
	private Boolean grasticUlcer;
	private Boolean thyroid;
	private Boolean limitationOpenCloseMouth;
	private Boolean noiseJawOpenCloseMouth;
	private Boolean herpesThrush;
	private Boolean bitLipsNailsHabit;
	private Boolean smokeHabit;
	private Integer cigarettesDayHabit;
	private Boolean citrusFoodsHabit;
	private Boolean bitObjectsHabit;
	private Boolean toothClenchHabit;
	private Boolean mouthBreathHabit;
	private String obs;

	public CrmOdontologyPersonalRecord() {
	}

	public CrmOdontologyPersonalRecord(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyPersonalRecord(CrmAppointment crmAppointment,
			Boolean medicalTreatment, Boolean medicine, Boolean surgery,
			Boolean bloodTransfusion, Boolean bloodPressureHigh,
			Boolean bloodPressureLow, Boolean penicillinAllergy,
			Boolean anesthesiaAllergy, Boolean aspirinAllergy,
			String otherAllergy, Boolean excesivesBlood, Boolean bloodProblem,
			Boolean anemiaLeukemiaHemophilia, Boolean hiv, Boolean retroviral,
			Boolean pregnant, Boolean contraceptives,
			Boolean venereaslDiseases, Boolean heartProblems,
			Boolean hepatitis, Boolean asthma, Boolean rheumaticFever,
			Boolean diabetes, Boolean grasticUlcer, Boolean thyroid,
			Boolean limitationOpenCloseMouth, Boolean noiseJawOpenCloseMouth,
			Boolean herpesThrush, Boolean bitLipsNailsHabit,
			Boolean smokeHabit, Integer cigarettesDayHabit,
			Boolean citrusFoodsHabit, Boolean bitObjectsHabit,
			Boolean toothClenchHabit, Boolean mouthBreathHabit, String obs) {
		this.crmAppointment = crmAppointment;
		this.medicalTreatment = medicalTreatment;
		this.medicine = medicine;
		this.surgery = surgery;
		this.bloodTransfusion = bloodTransfusion;
		this.bloodPressureHigh = bloodPressureHigh;
		this.bloodPressureLow = bloodPressureLow;
		this.penicillinAllergy = penicillinAllergy;
		this.anesthesiaAllergy = anesthesiaAllergy;
		this.aspirinAllergy = aspirinAllergy;
		this.otherAllergy = otherAllergy;
		this.excesivesBlood = excesivesBlood;
		this.bloodProblem = bloodProblem;
		this.anemiaLeukemiaHemophilia = anemiaLeukemiaHemophilia;
		this.hiv = hiv;
		this.retroviral = retroviral;
		this.pregnant = pregnant;
		this.contraceptives = contraceptives;
		this.venereaslDiseases = venereaslDiseases;
		this.heartProblems = heartProblems;
		this.hepatitis = hepatitis;
		this.asthma = asthma;
		this.rheumaticFever = rheumaticFever;
		this.diabetes = diabetes;
		this.grasticUlcer = grasticUlcer;
		this.thyroid = thyroid;
		this.limitationOpenCloseMouth = limitationOpenCloseMouth;
		this.noiseJawOpenCloseMouth = noiseJawOpenCloseMouth;
		this.herpesThrush = herpesThrush;
		this.bitLipsNailsHabit = bitLipsNailsHabit;
		this.smokeHabit = smokeHabit;
		this.cigarettesDayHabit = cigarettesDayHabit;
		this.citrusFoodsHabit = citrusFoodsHabit;
		this.bitObjectsHabit = bitObjectsHabit;
		this.toothClenchHabit = toothClenchHabit;
		this.mouthBreathHabit = mouthBreathHabit;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "medical_treatment")
	public Boolean getMedicalTreatment() {
		return this.medicalTreatment;
	}

	public void setMedicalTreatment(Boolean medicalTreatment) {
		this.medicalTreatment = medicalTreatment;
	}

	@Column(name = "medicine")
	public Boolean getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Boolean medicine) {
		this.medicine = medicine;
	}

	@Column(name = "surgery")
	public Boolean getSurgery() {
		return this.surgery;
	}

	public void setSurgery(Boolean surgery) {
		this.surgery = surgery;
	}

	@Column(name = "blood_transfusion")
	public Boolean getBloodTransfusion() {
		return this.bloodTransfusion;
	}

	public void setBloodTransfusion(Boolean bloodTransfusion) {
		this.bloodTransfusion = bloodTransfusion;
	}

	@Column(name = "blood_pressure_high")
	public Boolean getBloodPressureHigh() {
		return this.bloodPressureHigh;
	}

	public void setBloodPressureHigh(Boolean bloodPressureHigh) {
		this.bloodPressureHigh = bloodPressureHigh;
	}

	@Column(name = "blood_pressure_low")
	public Boolean getBloodPressureLow() {
		return this.bloodPressureLow;
	}

	public void setBloodPressureLow(Boolean bloodPressureLow) {
		this.bloodPressureLow = bloodPressureLow;
	}

	@Column(name = "penicillin_allergy")
	public Boolean getPenicillinAllergy() {
		return this.penicillinAllergy;
	}

	public void setPenicillinAllergy(Boolean penicillinAllergy) {
		this.penicillinAllergy = penicillinAllergy;
	}

	@Column(name = "anesthesia_allergy")
	public Boolean getAnesthesiaAllergy() {
		return this.anesthesiaAllergy;
	}

	public void setAnesthesiaAllergy(Boolean anesthesiaAllergy) {
		this.anesthesiaAllergy = anesthesiaAllergy;
	}

	@Column(name = "aspirin_allergy")
	public Boolean getAspirinAllergy() {
		return this.aspirinAllergy;
	}

	public void setAspirinAllergy(Boolean aspirinAllergy) {
		this.aspirinAllergy = aspirinAllergy;
	}

	@Column(name = "other_allergy", length = 65535)
	public String getOtherAllergy() {
		return this.otherAllergy;
	}

	public void setOtherAllergy(String otherAllergy) {
		this.otherAllergy = otherAllergy;
	}

	@Column(name = "excesives_blood")
	public Boolean getExcesivesBlood() {
		return this.excesivesBlood;
	}

	public void setExcesivesBlood(Boolean excesivesBlood) {
		this.excesivesBlood = excesivesBlood;
	}

	@Column(name = "blood_problem")
	public Boolean getBloodProblem() {
		return this.bloodProblem;
	}

	public void setBloodProblem(Boolean bloodProblem) {
		this.bloodProblem = bloodProblem;
	}

	@Column(name = "anemia_leukemia_hemophilia")
	public Boolean getAnemiaLeukemiaHemophilia() {
		return this.anemiaLeukemiaHemophilia;
	}

	public void setAnemiaLeukemiaHemophilia(Boolean anemiaLeukemiaHemophilia) {
		this.anemiaLeukemiaHemophilia = anemiaLeukemiaHemophilia;
	}

	@Column(name = "hiv")
	public Boolean getHiv() {
		return this.hiv;
	}

	public void setHiv(Boolean hiv) {
		this.hiv = hiv;
	}

	@Column(name = "retroviral")
	public Boolean getRetroviral() {
		return this.retroviral;
	}

	public void setRetroviral(Boolean retroviral) {
		this.retroviral = retroviral;
	}

	@Column(name = "pregnant")
	public Boolean getPregnant() {
		return this.pregnant;
	}

	public void setPregnant(Boolean pregnant) {
		this.pregnant = pregnant;
	}

	@Column(name = "contraceptives")
	public Boolean getContraceptives() {
		return this.contraceptives;
	}

	public void setContraceptives(Boolean contraceptives) {
		this.contraceptives = contraceptives;
	}

	@Column(name = "venereasl_diseases")
	public Boolean getVenereaslDiseases() {
		return this.venereaslDiseases;
	}

	public void setVenereaslDiseases(Boolean venereaslDiseases) {
		this.venereaslDiseases = venereaslDiseases;
	}

	@Column(name = "heart_problems")
	public Boolean getHeartProblems() {
		return this.heartProblems;
	}

	public void setHeartProblems(Boolean heartProblems) {
		this.heartProblems = heartProblems;
	}

	@Column(name = "hepatitis")
	public Boolean getHepatitis() {
		return this.hepatitis;
	}

	public void setHepatitis(Boolean hepatitis) {
		this.hepatitis = hepatitis;
	}

	@Column(name = "asthma")
	public Boolean getAsthma() {
		return this.asthma;
	}

	public void setAsthma(Boolean asthma) {
		this.asthma = asthma;
	}

	@Column(name = "rheumatic_fever")
	public Boolean getRheumaticFever() {
		return this.rheumaticFever;
	}

	public void setRheumaticFever(Boolean rheumaticFever) {
		this.rheumaticFever = rheumaticFever;
	}

	@Column(name = "diabetes")
	public Boolean getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(Boolean diabetes) {
		this.diabetes = diabetes;
	}

	@Column(name = "grastic_ulcer")
	public Boolean getGrasticUlcer() {
		return this.grasticUlcer;
	}

	public void setGrasticUlcer(Boolean grasticUlcer) {
		this.grasticUlcer = grasticUlcer;
	}

	@Column(name = "thyroid")
	public Boolean getThyroid() {
		return this.thyroid;
	}

	public void setThyroid(Boolean thyroid) {
		this.thyroid = thyroid;
	}

	@Column(name = "limitation_open_close_mouth")
	public Boolean getLimitationOpenCloseMouth() {
		return this.limitationOpenCloseMouth;
	}

	public void setLimitationOpenCloseMouth(Boolean limitationOpenCloseMouth) {
		this.limitationOpenCloseMouth = limitationOpenCloseMouth;
	}

	@Column(name = "noise_jaw_open_close_mouth")
	public Boolean getNoiseJawOpenCloseMouth() {
		return this.noiseJawOpenCloseMouth;
	}

	public void setNoiseJawOpenCloseMouth(Boolean noiseJawOpenCloseMouth) {
		this.noiseJawOpenCloseMouth = noiseJawOpenCloseMouth;
	}

	@Column(name = "herpes_thrush")
	public Boolean getHerpesThrush() {
		return this.herpesThrush;
	}

	public void setHerpesThrush(Boolean herpesThrush) {
		this.herpesThrush = herpesThrush;
	}

	@Column(name = "bit_lips_nails_habit")
	public Boolean getBitLipsNailsHabit() {
		return this.bitLipsNailsHabit;
	}

	public void setBitLipsNailsHabit(Boolean bitLipsNailsHabit) {
		this.bitLipsNailsHabit = bitLipsNailsHabit;
	}

	@Column(name = "smoke_habit")
	public Boolean getSmokeHabit() {
		return this.smokeHabit;
	}

	public void setSmokeHabit(Boolean smokeHabit) {
		this.smokeHabit = smokeHabit;
	}

	@Column(name = "cigarettes_day_habit")
	public Integer getCigarettesDayHabit() {
		return this.cigarettesDayHabit;
	}

	public void setCigarettesDayHabit(Integer cigarettesDayHabit) {
		this.cigarettesDayHabit = cigarettesDayHabit;
	}

	@Column(name = "citrus_foods_habit")
	public Boolean getCitrusFoodsHabit() {
		return this.citrusFoodsHabit;
	}

	public void setCitrusFoodsHabit(Boolean citrusFoodsHabit) {
		this.citrusFoodsHabit = citrusFoodsHabit;
	}

	@Column(name = "bit_objects_habit")
	public Boolean getBitObjectsHabit() {
		return this.bitObjectsHabit;
	}

	public void setBitObjectsHabit(Boolean bitObjectsHabit) {
		this.bitObjectsHabit = bitObjectsHabit;
	}

	@Column(name = "tooth_clench_habit")
	public Boolean getToothClenchHabit() {
		return this.toothClenchHabit;
	}

	public void setToothClenchHabit(Boolean toothClenchHabit) {
		this.toothClenchHabit = toothClenchHabit;
	}

	@Column(name = "mouth_breath_habit")
	public Boolean getMouthBreathHabit() {
		return this.mouthBreathHabit;
	}

	public void setMouthBreathHabit(Boolean mouthBreathHabit) {
		this.mouthBreathHabit = mouthBreathHabit;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
