package co.com.tactusoft.crm.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmOdontologyTempJoint generated by hbm2java
 */
@Entity
@Table(name = "crm_odontology_temp_joint", catalog = "crm_db")
public class CrmOdontologyTempJoint implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private Boolean openingNoise;
	private Boolean closureNoise;
	private Boolean laterality;
	private Boolean openingDeviaton;
	private Boolean closureDeviaton;
	private Boolean lateralityDeviaton;
	private Boolean openingPain;
	private Boolean closurePain;
	private Boolean lateralityPain;
	private Boolean openingFatigue;
	private Boolean closureFatigue;
	private Boolean lateralityFatigue;
	private String obs;

	public CrmOdontologyTempJoint() {
	}

	public CrmOdontologyTempJoint(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	public CrmOdontologyTempJoint(CrmAppointment crmAppointment,
			Boolean openingNoise, Boolean closureNoise, Boolean laterality,
			Boolean openingDeviaton, Boolean closureDeviaton,
			Boolean lateralityDeviaton, Boolean openingPain,
			Boolean closurePain, Boolean lateralityPain,
			Boolean openingFatigue, Boolean closureFatigue,
			Boolean lateralityFatigue, String obs) {
		this.crmAppointment = crmAppointment;
		this.openingNoise = openingNoise;
		this.closureNoise = closureNoise;
		this.laterality = laterality;
		this.openingDeviaton = openingDeviaton;
		this.closureDeviaton = closureDeviaton;
		this.lateralityDeviaton = lateralityDeviaton;
		this.openingPain = openingPain;
		this.closurePain = closurePain;
		this.lateralityPain = lateralityPain;
		this.openingFatigue = openingFatigue;
		this.closureFatigue = closureFatigue;
		this.lateralityFatigue = lateralityFatigue;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "opening_noise")
	public Boolean getOpeningNoise() {
		return this.openingNoise;
	}

	public void setOpeningNoise(Boolean openingNoise) {
		this.openingNoise = openingNoise;
	}

	@Column(name = "closure_noise")
	public Boolean getClosureNoise() {
		return this.closureNoise;
	}

	public void setClosureNoise(Boolean closureNoise) {
		this.closureNoise = closureNoise;
	}

	@Column(name = "laterality")
	public Boolean getLaterality() {
		return this.laterality;
	}

	public void setLaterality(Boolean laterality) {
		this.laterality = laterality;
	}

	@Column(name = "opening_deviaton")
	public Boolean getOpeningDeviaton() {
		return this.openingDeviaton;
	}

	public void setOpeningDeviaton(Boolean openingDeviaton) {
		this.openingDeviaton = openingDeviaton;
	}

	@Column(name = "closure_deviaton")
	public Boolean getClosureDeviaton() {
		return this.closureDeviaton;
	}

	public void setClosureDeviaton(Boolean closureDeviaton) {
		this.closureDeviaton = closureDeviaton;
	}

	@Column(name = "laterality_deviaton")
	public Boolean getLateralityDeviaton() {
		return this.lateralityDeviaton;
	}

	public void setLateralityDeviaton(Boolean lateralityDeviaton) {
		this.lateralityDeviaton = lateralityDeviaton;
	}

	@Column(name = "opening_pain")
	public Boolean getOpeningPain() {
		return this.openingPain;
	}

	public void setOpeningPain(Boolean openingPain) {
		this.openingPain = openingPain;
	}

	@Column(name = "closure_pain")
	public Boolean getClosurePain() {
		return this.closurePain;
	}

	public void setClosurePain(Boolean closurePain) {
		this.closurePain = closurePain;
	}

	@Column(name = "laterality_pain")
	public Boolean getLateralityPain() {
		return this.lateralityPain;
	}

	public void setLateralityPain(Boolean lateralityPain) {
		this.lateralityPain = lateralityPain;
	}

	@Column(name = "opening_fatigue")
	public Boolean getOpeningFatigue() {
		return this.openingFatigue;
	}

	public void setOpeningFatigue(Boolean openingFatigue) {
		this.openingFatigue = openingFatigue;
	}

	@Column(name = "closure_fatigue")
	public Boolean getClosureFatigue() {
		return this.closureFatigue;
	}

	public void setClosureFatigue(Boolean closureFatigue) {
		this.closureFatigue = closureFatigue;
	}

	@Column(name = "laterality_fatigue")
	public Boolean getLateralityFatigue() {
		return this.lateralityFatigue;
	}

	public void setLateralityFatigue(Boolean lateralityFatigue) {
		this.lateralityFatigue = lateralityFatigue;
	}

	@Column(name = "obs", length = 65535)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
