package co.com.tactusoft.crm.model.entities;

// Generated 24-abr-2013 14:52:22 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwRipsAppointment generated by hbm2java
 */
@Entity
@Table(name = "vw_rips_appointment", catalog = "crm_db")
public class VwRipsAppointment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private VwRipsAppointmentId id;

	public VwRipsAppointment() {
	}

	public VwRipsAppointment(VwRipsAppointmentId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idBranch", column = @Column(name = "id_branch", nullable = false, scale = 0)),
			@AttributeOverride(name = "idBill", column = @Column(name = "id_bill", nullable = false, length = 30)),
			@AttributeOverride(name = "clinic", column = @Column(name = "clinic", nullable = false, length = 12)),
			@AttributeOverride(name = "docType", column = @Column(name = "doc_type", length = 2)),
			@AttributeOverride(name = "doc", column = @Column(name = "doc", length = 45)),
			@AttributeOverride(name = "appointmentDate", column = @Column(name = "appointment_date", length = 10)),
			@AttributeOverride(name = "appointmentType", column = @Column(name = "appointment_type", nullable = false)),
			@AttributeOverride(name = "autorization", column = @Column(name = "autorization", nullable = false, length = 0)),
			@AttributeOverride(name = "appointmentCode", column = @Column(name = "appointment_code", nullable = false, length = 6)),
			@AttributeOverride(name = "appointmentTarget", column = @Column(name = "appointment_target", nullable = false)),
			@AttributeOverride(name = "appointmentExternal", column = @Column(name = "appointment_external", nullable = false)),
			@AttributeOverride(name = "diagnosis1", column = @Column(name = "diagnosis_1", length = 4)),
			@AttributeOverride(name = "diagnosis2", column = @Column(name = "diagnosis_2", nullable = false, length = 0)),
			@AttributeOverride(name = "diagnosis3", column = @Column(name = "diagnosis_3", nullable = false, length = 0)),
			@AttributeOverride(name = "diagnosis4", column = @Column(name = "diagnosis_4", nullable = false, length = 0)),
			@AttributeOverride(name = "diagnosisType", column = @Column(name = "diagnosis_type", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 10)),
			@AttributeOverride(name = "quote", column = @Column(name = "quote", nullable = false)),
			@AttributeOverride(name = "total", column = @Column(name = "total", precision = 10)) })
	public VwRipsAppointmentId getId() {
		return this.id;
	}

	public void setId(VwRipsAppointmentId id) {
		this.id = id;
	}

}
