package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmBranch generated by hbm2java
 */
@Entity
@Table(name = "crm_branch", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmBranch implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String name;
	private String formula;
	private Integer state;
	private Set<CrmUserBrach> crmUserBrachs = new HashSet<CrmUserBrach>(0);

	public CrmBranch() {
	}

	public CrmBranch(BigDecimal id, String formula) {
		this.id = id;
		this.formula = formula;
	}

	public CrmBranch(BigDecimal id, String code, String name, String formula,
			Integer state, Set<CrmUserBrach> crmUserBrachs) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.formula = formula;
		this.state = state;
		this.crmUserBrachs = crmUserBrachs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmBranch")
	public Set<CrmUserBrach> getCrmUserBrachs() {
		return this.crmUserBrachs;
	}

	public void setCrmUserBrachs(Set<CrmUserBrach> crmUserBrachs) {
		this.crmUserBrachs = crmUserBrachs;
	}

	@Column(name = "formula", nullable = false, length = 4)
	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

}
