package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrmCaseStudy generated by hbm2java
 */
@Entity
@Table(name = "crm_case_study", catalog = "crm_db")
public class CrmCaseStudy implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmDoctor crmDoctor;
	private CrmPatient crmPatient;
	private Date startDate;
	private Date endDate;
	private String patology;
	private String reason;
	private String perc1;
	private String perc2;
	private String perc3;
	private String perc4;
	private String criteria;

	public CrmCaseStudy() {
	}

	public CrmCaseStudy(CrmDoctor crmDoctor, CrmPatient crmPatient,
			Date startDate, Date endDate, String patology, String reason,
			String criteria) {
		this.crmDoctor = crmDoctor;
		this.crmPatient = crmPatient;
		this.startDate = startDate;
		this.endDate = endDate;
		this.patology = patology;
		this.reason = reason;
		this.criteria = criteria;
	}

	public CrmCaseStudy(CrmDoctor crmDoctor, CrmPatient crmPatient,
			Date startDate, Date endDate, String patology, String reason,
			String perc1, String perc2, String perc3, String perc4,
			String criteria) {
		this.crmDoctor = crmDoctor;
		this.crmPatient = crmPatient;
		this.startDate = startDate;
		this.endDate = endDate;
		this.patology = patology;
		this.reason = reason;
		this.perc1 = perc1;
		this.perc2 = perc2;
		this.perc3 = perc3;
		this.perc4 = perc4;
		this.criteria = criteria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_doctor", nullable = false)
	public CrmDoctor getCrmDoctor() {
		return this.crmDoctor;
	}

	public void setCrmDoctor(CrmDoctor crmDoctor) {
		this.crmDoctor = crmDoctor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "patology", nullable = false, length = 65535)
	public String getPatology() {
		return this.patology;
	}

	public void setPatology(String patology) {
		this.patology = patology;
	}

	@Column(name = "reason", nullable = false, length = 65535)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "perc_1", length = 3)
	public String getPerc1() {
		return this.perc1;
	}

	public void setPerc1(String perc1) {
		this.perc1 = perc1;
	}

	@Column(name = "perc_2", length = 3)
	public String getPerc2() {
		return this.perc2;
	}

	public void setPerc2(String perc2) {
		this.perc2 = perc2;
	}

	@Column(name = "perc_3", length = 3)
	public String getPerc3() {
		return this.perc3;
	}

	public void setPerc3(String perc3) {
		this.perc3 = perc3;
	}

	@Column(name = "perc_4", length = 3)
	public String getPerc4() {
		return this.perc4;
	}

	public void setPerc4(String perc4) {
		this.perc4 = perc4;
	}

	@Column(name = "criteria", nullable = false, length = 65535)
	public String getCriteria() {
		return this.criteria;
	}

	public void setCriteria(String criteria) {
		this.criteria = criteria;
	}

}
