package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmCountry generated by hbm2java
 */
@Entity
@Table(name = "crm_country", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmCountry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String name;
	private String currencyIso;
	private Boolean automatic;
	private Set<CrmRegion> crmRegions = new HashSet<CrmRegion>(0);

	public CrmCountry() {
	}

	public CrmCountry(BigDecimal id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public CrmCountry(BigDecimal id, String code, String name,
			String currencyIso, Boolean automatic, Set<CrmRegion> crmRegions) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.currencyIso = currencyIso;
		this.automatic = automatic;
		this.crmRegions = crmRegions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "currency_iso", length = 3)
	public String getCurrencyIso() {
		return this.currencyIso;
	}

	public void setCurrencyIso(String currencyIso) {
		this.currencyIso = currencyIso;
	}

	@Column(name = "automatic")
	public Boolean getAutomatic() {
		return this.automatic;
	}

	public void setAutomatic(Boolean automatic) {
		this.automatic = automatic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCountry")
	@OrderBy("name")
	public Set<CrmRegion> getCrmRegions() {
		return this.crmRegions;
	}

	public void setCrmRegions(Set<CrmRegion> crmRegions) {
		this.crmRegions = crmRegions;
	}

}
