package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmHistoryOrganometry generated by hbm2java
 */
@Entity
@Table(name = "crm_history_organometry", catalog = "crm_db")
public class CrmHistoryOrganometry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmPatient crmPatient;
	private Boolean organometryCheck;
	private String organometryAnalysis;

	public CrmHistoryOrganometry() {
	}

	public CrmHistoryOrganometry(BigDecimal id, CrmPatient crmPatient) {
		this.id = id;
		this.crmPatient = crmPatient;
	}

	public CrmHistoryOrganometry(BigDecimal id, CrmPatient crmPatient,
			Boolean organometryCheck, String organometryAnalysis) {
		this.id = id;
		this.crmPatient = crmPatient;
		this.organometryCheck = organometryCheck;
		this.organometryAnalysis = organometryAnalysis;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public CrmPatient getCrmPatient() {
		return this.crmPatient;
	}

	public void setCrmPatient(CrmPatient crmPatient) {
		this.crmPatient = crmPatient;
	}

	@Column(name = "organometry_check")
	public Boolean getOrganometryCheck() {
		return this.organometryCheck;
	}

	public void setOrganometryCheck(Boolean organometryCheck) {
		this.organometryCheck = organometryCheck;
	}

	@Column(name = "organometry_analysis", length = 65535)
	public String getOrganometryAnalysis() {
		return this.organometryAnalysis;
	}

	public void setOrganometryAnalysis(String organometryAnalysis) {
		this.organometryAnalysis = organometryAnalysis;
	}

}
