package co.com.tactusoft.crm.model.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CrmHoliday generated by hbm2java
 */
@Entity
@Table(name = "crm_holiday", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "holiday"))
public class CrmHoliday implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String description;
	private Date holiday;

	public CrmHoliday() {
	}

	public CrmHoliday(int id) {
		this.id = id;
	}

	public CrmHoliday(int id, String description, Date holiday) {
		this.id = id;
		this.description = description;
		this.holiday = holiday;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "holiday", unique = true, length = 10)
	public Date getHoliday() {
		return this.holiday;
	}

	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}

}
