package co.com.tactusoft.crm.model.entities;

// Generated 20/06/2012 02:16:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmHistoryPhysique generated by hbm2java
 */
@Entity
@Table(name = "crm_history_physique", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "id_patient"))
public class CrmHistoryPhysique implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idPatient;
	private String physiqueTa;
	private String physiqueFc;
	private String physiqueFr;
	private String physiqueTo;
	private BigDecimal physiqueSize;
	private BigDecimal physiqueWeight;
	private String generalState;
	private String skull;
	private String chest;
	private String lungs;
	private String heart;
	private String abdomen;
	private String genitals;
	private String tips;
	private String highlights;
	private String skin;
	private String review;

	public CrmHistoryPhysique() {
	}

	public CrmHistoryPhysique(BigDecimal id, BigDecimal idPatient) {
		this.id = id;
		this.idPatient = idPatient;
	}

	public CrmHistoryPhysique(BigDecimal id, BigDecimal idPatient, String physiqueTa,
			String physiqueFc, String physiqueFr, String physiqueTo,
			BigDecimal physiqueSize, BigDecimal physiqueWeight,
			String generalState, String skull, String chest, String lungs,
			String heart, String abdomen, String genitals, String tips,
			String highlights, String skin, String review) {
		this.id = id;
		this.idPatient = idPatient;
		this.physiqueTa = physiqueTa;
		this.physiqueFc = physiqueFc;
		this.physiqueFr = physiqueFr;
		this.physiqueTo = physiqueTo;
		this.physiqueSize = physiqueSize;
		this.physiqueWeight = physiqueWeight;
		this.generalState = generalState;
		this.skull = skull;
		this.chest = chest;
		this.lungs = lungs;
		this.heart = heart;
		this.abdomen = abdomen;
		this.genitals = genitals;
		this.tips = tips;
		this.highlights = highlights;
		this.skin = skin;
		this.review = review;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_patient", unique = true, nullable = false)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "physique_ta", length = 45)
	public String getPhysiqueTa() {
		return this.physiqueTa;
	}

	public void setPhysiqueTa(String physiqueTa) {
		this.physiqueTa = physiqueTa;
	}

	@Column(name = "physique_fc", length = 45)
	public String getPhysiqueFc() {
		return this.physiqueFc;
	}

	public void setPhysiqueFc(String physiqueFc) {
		this.physiqueFc = physiqueFc;
	}

	@Column(name = "physique_fr", length = 45)
	public String getPhysiqueFr() {
		return this.physiqueFr;
	}

	public void setPhysiqueFr(String physiqueFr) {
		this.physiqueFr = physiqueFr;
	}

	@Column(name = "physique_to", length = 45)
	public String getPhysiqueTo() {
		return this.physiqueTo;
	}

	public void setPhysiqueTo(String physiqueTo) {
		this.physiqueTo = physiqueTo;
	}

	@Column(name = "physique_size", precision = 5)
	public BigDecimal getPhysiqueSize() {
		return this.physiqueSize;
	}

	public void setPhysiqueSize(BigDecimal physiqueSize) {
		this.physiqueSize = physiqueSize;
	}

	@Column(name = "physique_weight", precision = 5)
	public BigDecimal getPhysiqueWeight() {
		return this.physiqueWeight;
	}

	public void setPhysiqueWeight(BigDecimal physiqueWeight) {
		this.physiqueWeight = physiqueWeight;
	}

	@Column(name = "general_state", length = 1000)
	public String getGeneralState() {
		return this.generalState;
	}

	public void setGeneralState(String generalState) {
		this.generalState = generalState;
	}

	@Column(name = "skull", length = 1000)
	public String getSkull() {
		return this.skull;
	}

	public void setSkull(String skull) {
		this.skull = skull;
	}

	@Column(name = "chest", length = 1000)
	public String getChest() {
		return this.chest;
	}

	public void setChest(String chest) {
		this.chest = chest;
	}

	@Column(name = "lungs", length = 1000)
	public String getLungs() {
		return this.lungs;
	}

	public void setLungs(String lungs) {
		this.lungs = lungs;
	}

	@Column(name = "heart", length = 1000)
	public String getHeart() {
		return this.heart;
	}

	public void setHeart(String heart) {
		this.heart = heart;
	}

	@Column(name = "abdomen", length = 1000)
	public String getAbdomen() {
		return this.abdomen;
	}

	public void setAbdomen(String abdomen) {
		this.abdomen = abdomen;
	}

	@Column(name = "genitals", length = 1000)
	public String getGenitals() {
		return this.genitals;
	}

	public void setGenitals(String genitals) {
		this.genitals = genitals;
	}

	@Column(name = "tips", length = 1000)
	public String getTips() {
		return this.tips;
	}

	public void setTips(String tips) {
		this.tips = tips;
	}

	@Column(name = "highlights", length = 1000)
	public String getHighlights() {
		return this.highlights;
	}

	public void setHighlights(String highlights) {
		this.highlights = highlights;
	}

	@Column(name = "skin", length = 1000)
	public String getSkin() {
		return this.skin;
	}

	public void setSkin(String skin) {
		this.skin = skin;
	}

	@Column(name = "review", length = 1000)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

}
