package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmNote generated by hbm2java
 */
@Entity
@Table(name = "crm_note", catalog = "crm_db")
public class CrmNote implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmAppointment crmAppointment;
	private String noteType;
	private String note;

	public CrmNote() {
	}

	public CrmNote(BigDecimal id, CrmAppointment crmAppointment,
			String noteType, String note) {
		this.id = id;
		this.crmAppointment = crmAppointment;
		this.noteType = noteType;
		this.note = note;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return this.crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "note_type", nullable = false, length = 45)
	public String getNoteType() {
		return this.noteType;
	}

	public void setNoteType(String noteType) {
		this.noteType = noteType;
	}

	@Column(name = "note", nullable = false, length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
