package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwDoctorScheduleId generated by hbm2java
 */
@Embeddable
public class VwDoctorScheduleId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal idDoctor;
	private String firstName;
	private String firstSurname;
	private BigDecimal idBranch;
	private int day;

	public VwDoctorScheduleId() {
	}

	public VwDoctorScheduleId(BigDecimal idDoctor, String firstName,
			String firstSurname, BigDecimal idBranch, int day) {
		this.idDoctor = idDoctor;
		this.firstName = firstName;
		this.firstSurname = firstSurname;
		this.idBranch = idBranch;
		this.day = day;
	}

	@Column(name = "id_doctor", nullable = false, scale = 0)
	public BigDecimal getIdDoctor() {
		return this.idDoctor;
	}

	public void setIdDoctor(BigDecimal idDoctor) {
		this.idDoctor = idDoctor;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "first_surname", nullable = false, length = 45)
	public String getFirstSurname() {
		return this.firstSurname;
	}

	public void setFirstSurname(String firstSurname) {
		this.firstSurname = firstSurname;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "day", nullable = false)
	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwDoctorScheduleId))
			return false;
		VwDoctorScheduleId castOther = (VwDoctorScheduleId) other;

		return ((this.getIdDoctor() == castOther.getIdDoctor()) || (this
				.getIdDoctor() != null && castOther.getIdDoctor() != null && this
				.getIdDoctor().equals(castOther.getIdDoctor())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this
						.getFirstName() != null
						&& castOther.getFirstName() != null && this
						.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getFirstSurname() == castOther.getFirstSurname()) || (this
						.getFirstSurname() != null
						&& castOther.getFirstSurname() != null && this
						.getFirstSurname().equals(castOther.getFirstSurname())))
				&& ((this.getIdBranch() == castOther.getIdBranch()) || (this
						.getIdBranch() != null
						&& castOther.getIdBranch() != null && this
						.getIdBranch().equals(castOther.getIdBranch())))
				&& (this.getDay() == castOther.getDay());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDoctor() == null ? 0 : this.getIdDoctor().hashCode());
		result = 37 * result
				+ (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37
				* result
				+ (getFirstSurname() == null ? 0 : this.getFirstSurname()
						.hashCode());
		result = 37 * result
				+ (getIdBranch() == null ? 0 : this.getIdBranch().hashCode());
		result = 37 * result + this.getDay();
		return result;
	}

}
