package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmCie generated by hbm2java
 */
@Entity
@Table(name = "crm_cie", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmCie implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String description;
	private String cieType;
	private String sapCode;
	private Set<CrmDiagnosis> crmDiagnosises = new HashSet<CrmDiagnosis>(0);
	private Set<CrmCieMaterial> crmCieMaterials = new HashSet<CrmCieMaterial>(0);
	private Set<CrmMedication> crmMedications = new HashSet<CrmMedication>(0);

	public CrmCie() {
	}

	public CrmCie(BigDecimal id) {
		this.id = id;
	}

	public CrmCie(BigDecimal id, String code, String description,
			Set<CrmDiagnosis> crmDiagnosises, String cieType, String sapCode,
			Set<CrmCieMaterial> crmCieMaterials,
			Set<CrmMedication> crmMedications) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.crmDiagnosises = crmDiagnosises;
		this.cieType = cieType;
		this.sapCode = sapCode;
		this.crmCieMaterials = crmCieMaterials;
		this.crmMedications = crmMedications;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 4)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cie_type", length = 45)
	public String getCieType() {
		return cieType;
	}

	public void setCieType(String cieType) {
		this.cieType = cieType;
	}

	@Column(name = "sap_code", length = 20)
	public String getSapCode() {
		return sapCode;
	}

	public void setSapCode(String sapCode) {
		this.sapCode = sapCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCie")
	public Set<CrmDiagnosis> getCrmDiagnosises() {
		return this.crmDiagnosises;
	}

	public void setCrmDiagnosises(Set<CrmDiagnosis> crmDiagnosises) {
		this.crmDiagnosises = crmDiagnosises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCie")
	public Set<CrmCieMaterial> getCrmCieMaterials() {
		return this.crmCieMaterials;
	}

	public void setCrmCieMaterials(Set<CrmCieMaterial> crmCieMaterials) {
		this.crmCieMaterials = crmCieMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCie")
	public Set<CrmMedication> getCrmMedications() {
		return this.crmMedications;
	}

	public void setCrmMedications(Set<CrmMedication> crmMedications) {
		this.crmMedications = crmMedications;
	}

}
