package co.com.tactusoft.crm.model.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmJob generated by hbm2java
 */
@Entity
@Table(name = "crm_job", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmJob implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String code;
	private String name;
	private int status;
	private Set<CrmAccount> crmAccounts = new HashSet<CrmAccount>(0);

	public CrmJob() {
	}

	public CrmJob(String code, String name, int status) {
		this.code = code;
		this.name = name;
		this.status = status;
	}

	public CrmJob(String code, String name, int status,
			Set<CrmAccount> crmAccounts) {
		this.code = code;
		this.name = name;
		this.status = status;
		this.crmAccounts = crmAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int isStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmJob")
	public Set<CrmAccount> getCrmAccounts() {
		return this.crmAccounts;
	}

	public void setCrmAccounts(Set<CrmAccount> crmAccounts) {
		this.crmAccounts = crmAccounts;
	}

}
