package co.com.tactusoft.medical.model.entities;

// Generated 22/03/2012 07:29:58 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MedBodyDetail generated by hbm2java
 */
@Entity
@Table(name = "med_body_detail", catalog = "medical_db")
public class MedBodyDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private MedBody medBody;
	private String title;
	private String resourceType;
	private String urlLink;
	private BigDecimal idTopic;
	private String gender;
	private int state;

	public MedBodyDetail() {
	}

	public MedBodyDetail(BigDecimal id, MedBody medBody, String title,
			String resourceType, String urlLink, String gender, int state) {
		this.id = id;
		this.medBody = medBody;
		this.title = title;
		this.resourceType = resourceType;
		this.urlLink = urlLink;
		this.gender = gender;
		this.state = state;
	}

	public MedBodyDetail(BigDecimal id, MedBody medBody, String title,
			String resourceType, String urlLink, BigDecimal idTopic,
			String gender, int state) {
		this.id = id;
		this.medBody = medBody;
		this.title = title;
		this.resourceType = resourceType;
		this.urlLink = urlLink;
		this.idTopic = idTopic;
		this.gender = gender;
		this.state = state;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_body", nullable = false)
	public MedBody getMedBody() {
		return this.medBody;
	}

	public void setMedBody(MedBody medBody) {
		this.medBody = medBody;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "resource_type", nullable = false, length = 15)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "url_link", nullable = false, length = 4000)
	public String getUrlLink() {
		return this.urlLink;
	}

	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink;
	}

	@Column(name = "id_topic", scale = 0)
	public BigDecimal getIdTopic() {
		return this.idTopic;
	}

	public void setIdTopic(BigDecimal idTopic) {
		this.idTopic = idTopic;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
