package co.com.tactusoft.medical.model.entities;

// Generated 19/03/2012 05:54:55 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedBody generated by hbm2java
 */
@Entity
@Table(name = "med_body", catalog = "medical_db")
public class MedBody implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private BigDecimal x;
	private BigDecimal y;
	private int state;
	private Set<MedBodyDetail> medBodyDetails = new HashSet<MedBodyDetail>(0);

	public MedBody() {
	}

	public MedBody(BigDecimal id, String name, int state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public MedBody(BigDecimal id, String name, BigDecimal x, BigDecimal y,
			int state, Set<MedBodyDetail> medBodyDetails) {
		this.id = id;
		this.name = name;
		this.x = x;
		this.y = y;
		this.state = state;
		this.medBodyDetails = medBodyDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "x", scale = 5)
	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	@Column(name = "y", scale = 5)
	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medBody")
	public Set<MedBodyDetail> getMedBodyDetails() {
		return this.medBodyDetails;
	}

	public void setMedBodyDetails(Set<MedBodyDetail> medBodyDetails) {
		this.medBodyDetails = medBodyDetails;
	}

}
