package co.com.tactusoft.medical.model.entities;

// Generated 5/03/2012 02:36:02 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MedQuestion generated by hbm2java
 */
@Entity
@Table(name = "med_question", catalog = "medical_db")
public class MedQuestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private MedTopic medTopic;
	private String name;
	private String typeQuestion;
	private String resourceType;
	private String urlLink;
	private String image;
	private String typeVideo;
	private String urlVideo;
	private BigDecimal idParent;
	private BigDecimal positive;
	private BigDecimal negative;
	private Integer orderQuestion;

	public MedQuestion() {
	}

	public MedQuestion(BigDecimal id, MedTopic medTopic, String name,
			String typeQuestion) {
		this.id = id;
		this.medTopic = medTopic;
		this.name = name;
		this.typeQuestion = typeQuestion;
	}

	public MedQuestion(BigDecimal id, MedTopic medTopic, String name,
			String typeQuestion, String resourceType, String urlLink,
			String image, String typeVideo, String urlVideo,
			BigDecimal idParent, BigDecimal positive, BigDecimal negative,
			Integer orderQuestion) {
		this.id = id;
		this.medTopic = medTopic;
		this.name = name;
		this.typeQuestion = typeQuestion;
		this.resourceType = resourceType;
		this.urlLink = urlLink;
		this.image = image;
		this.typeVideo = typeVideo;
		this.urlVideo = urlVideo;
		this.idParent = idParent;
		this.positive = positive;
		this.negative = negative;
		this.orderQuestion = orderQuestion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_topic", nullable = false)
	public MedTopic getMedTopic() {
		return this.medTopic;
	}

	public void setMedTopic(MedTopic medTopic) {
		this.medTopic = medTopic;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type_question", nullable = false, length = 45)
	public String getTypeQuestion() {
		return this.typeQuestion;
	}

	public void setTypeQuestion(String typeQuestion) {
		this.typeQuestion = typeQuestion;
	}

	@Column(name = "resource_type", length = 15)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "url_link")
	public String getUrlLink() {
		return this.urlLink;
	}

	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "type_video", length = 45)
	public String getTypeVideo() {
		return this.typeVideo;
	}

	public void setTypeVideo(String typeVideo) {
		this.typeVideo = typeVideo;
	}

	@Column(name = "url_video")
	public String getUrlVideo() {
		return this.urlVideo;
	}

	public void setUrlVideo(String urlVideo) {
		this.urlVideo = urlVideo;
	}

	@Column(name = "id_parent", scale = 0)
	public BigDecimal getIdParent() {
		return this.idParent;
	}

	public void setIdParent(BigDecimal idParent) {
		this.idParent = idParent;
	}

	@Column(name = "positive", scale = 0)
	public BigDecimal getPositive() {
		return this.positive;
	}

	public void setPositive(BigDecimal positive) {
		this.positive = positive;
	}

	@Column(name = "negative", scale = 0)
	public BigDecimal getNegative() {
		return this.negative;
	}

	public void setNegative(BigDecimal negative) {
		this.negative = negative;
	}

	@Column(name = "order_question")
	public Integer getOrderQuestion() {
		return this.orderQuestion;
	}

	public void setOrderQuestion(Integer orderQuestion) {
		this.orderQuestion = orderQuestion;
	}

	@Transient
	public String getDetType() {
		String detType = null;

		if (typeQuestion.equals("ASSERTIVE")) {
			detType = "Sí/No";
		} else if (typeQuestion.equals("UNIQUE")) {
			detType = "Única Respuesta";
		} else if (typeQuestion.equals("MULTIPLE")) {
			detType = "Múltiple Respuesta";
		} else if (typeQuestion.equals("FINAL")) {
			detType = "Final";
		}

		return detType;
	}

}
