package co.com.tactusoft.kpi.model.entities;

// Generated 19/02/2012 08:20:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KpiCompany generated by hbm2java
 */
@Entity
@Table(name = "kpi_company", catalog = "kpi")
public class KpiCompany implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private String phone;
	private String legalRep;
	private String email;
	private int state;
	private Set<KpiHeader> kpiHeaders = new HashSet<KpiHeader>(0);

	public KpiCompany() {
	}

	public KpiCompany(BigDecimal id, String name, String email, int state) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.state = state;
	}

	public KpiCompany(BigDecimal id, String name, String phone,
			String legalRep, String email, int state, Set<KpiHeader> kpiHeaders) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.legalRep = legalRep;
		this.email = email;
		this.state = state;
		this.kpiHeaders = kpiHeaders;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "legal_rep")
	public String getLegalRep() {
		return this.legalRep;
	}

	public void setLegalRep(String legalRep) {
		this.legalRep = legalRep;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiCompany")
	public Set<KpiHeader> getKpiHeaders() {
		return this.kpiHeaders;
	}

	public void setKpiHeaders(Set<KpiHeader> kpiHeaders) {
		this.kpiHeaders = kpiHeaders;
	}

}
