package co.com.tactusoft.kpi.model.entities;

// Generated 26/02/2012 06:30:14 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KpiDailySumHoursId generated by hbm2java
 */
@Entity
@Table(name = "kpi_daily_sum_hours", catalog = "kpi_db")
public class KpiDailySumHours implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idDaily;
	private BigDecimal idDelay;
	private String nameDaily;
	private BigDecimal numHours;

	public KpiDailySumHours() {
	}

	public KpiDailySumHours(BigDecimal idDaily, BigDecimal idDelay,
			String nameDaily) {
		this.idDaily = idDaily;
		this.idDelay = idDelay;
		this.nameDaily = nameDaily;
	}

	public KpiDailySumHours(BigDecimal idDaily, BigDecimal idDelay,
			String nameDaily, BigDecimal numHours) {
		this.idDaily = idDaily;
		this.idDelay = idDelay;
		this.nameDaily = nameDaily;
		this.numHours = numHours;
	}

	@Column(name = "id_daily", nullable = false, scale = 0)
	public BigDecimal getIdDaily() {
		return this.idDaily;
	}

	public void setIdDaily(BigDecimal idDaily) {
		this.idDaily = idDaily;
	}

	@Id
	@Column(name = "id_delay", nullable = false, scale = 0)
	public BigDecimal getIdDelay() {
		return this.idDelay;
	}

	public void setIdDelay(BigDecimal idDelay) {
		this.idDelay = idDelay;
	}

	@Column(name = "name_daily", nullable = false)
	public String getNameDaily() {
		return this.nameDaily;
	}

	public void setNameDaily(String nameDaily) {
		this.nameDaily = nameDaily;
	}

	@Column(name = "num_hours", precision = 41)
	public BigDecimal getNumHours() {
		return this.numHours;
	}

	public void setNumHours(BigDecimal numHours) {
		this.numHours = numHours;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KpiDailySumHours))
			return false;
		KpiDailySumHours castOther = (KpiDailySumHours) other;

		return ((this.getIdDaily() == castOther.getIdDaily()) || (this
				.getIdDaily() != null && castOther.getIdDaily() != null && this
				.getIdDaily().equals(castOther.getIdDaily())))
				&& ((this.getIdDelay() == castOther.getIdDelay()) || (this
						.getIdDelay() != null && castOther.getIdDelay() != null && this
						.getIdDelay().equals(castOther.getIdDelay())))
				&& ((this.getNameDaily() == castOther.getNameDaily()) || (this
						.getNameDaily() != null
						&& castOther.getNameDaily() != null && this
						.getNameDaily().equals(castOther.getNameDaily())))
				&& ((this.getNumHours() == castOther.getNumHours()) || (this
						.getNumHours() != null
						&& castOther.getNumHours() != null && this
						.getNumHours().equals(castOther.getNumHours())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDaily() == null ? 0 : this.getIdDaily().hashCode());
		result = 37 * result
				+ (getIdDelay() == null ? 0 : this.getIdDelay().hashCode());
		result = 37 * result
				+ (getNameDaily() == null ? 0 : this.getNameDaily().hashCode());
		result = 37 * result
				+ (getNumHours() == null ? 0 : this.getNumHours().hashCode());
		return result;
	}

}
