package co.com.tactusoft.kpi.model.entities;

// Generated 19/02/2012 08:20:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KpiDelay generated by hbm2java
 */
@Entity
@Table(name = "kpi_delay", catalog = "kpi")
public class KpiDelay implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private String description;
	private int state;
	private Set<KpiConfig> kpiConfigs = new HashSet<KpiConfig>(0);

	public KpiDelay() {
	}

	public KpiDelay(BigDecimal id, String name, int state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public KpiDelay(BigDecimal id, String name, String description, int state,
			Set<KpiConfig> kpiConfigs) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.state = state;
		this.kpiConfigs = kpiConfigs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATE", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiDelay")
	public Set<KpiConfig> getKpiConfigs() {
		return this.kpiConfigs;
	}

	public void setKpiConfigs(Set<KpiConfig> kpiConfigs) {
		this.kpiConfigs = kpiConfigs;
	}

}
