package co.com.tactusoft.kpi.model.entities;

// Generated 26/02/2012 06:40:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KpiLastDayWeekId generated by hbm2java
 */
@Entity
@Table(name = "kpi_last_day_week", catalog = "kpi")
public class KpiLastDayWeek implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private Date currentDay;
	private String description;
	private Integer scheduledOrders;
	private Integer finishedOrders;
	private Integer failuresOrders;
	private BigDecimal idWeek;
	private int state;

	public KpiLastDayWeek() {
	}

	public KpiLastDayWeek(BigDecimal id, Date currentDay, BigDecimal idWeek,
			int state) {
		this.id = id;
		this.currentDay = currentDay;
		this.idWeek = idWeek;
		this.state = state;
	}

	public KpiLastDayWeek(BigDecimal id, Date currentDay, String description,
			Integer scheduledOrders, Integer finishedOrders,
			Integer failuresOrders, BigDecimal idWeek, int state) {
		this.id = id;
		this.currentDay = currentDay;
		this.description = description;
		this.scheduledOrders = scheduledOrders;
		this.finishedOrders = finishedOrders;
		this.failuresOrders = failuresOrders;
		this.idWeek = idWeek;
		this.state = state;
	}

	@Id
	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "current_day", nullable = false, length = 19)
	public Date getCurrentDay() {
		return this.currentDay;
	}

	public void setCurrentDay(Date currentDay) {
		this.currentDay = currentDay;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "scheduled_orders")
	public Integer getScheduledOrders() {
		return this.scheduledOrders;
	}

	public void setScheduledOrders(Integer scheduledOrders) {
		this.scheduledOrders = scheduledOrders;
	}

	@Column(name = "finished_orders")
	public Integer getFinishedOrders() {
		return this.finishedOrders;
	}

	public void setFinishedOrders(Integer finishedOrders) {
		this.finishedOrders = finishedOrders;
	}

	@Column(name = "failures_orders")
	public Integer getFailuresOrders() {
		return this.failuresOrders;
	}

	public void setFailuresOrders(Integer failuresOrders) {
		this.failuresOrders = failuresOrders;
	}

	@Column(name = "id_week", nullable = false, scale = 0)
	public BigDecimal getIdWeek() {
		return this.idWeek;
	}

	public void setIdWeek(BigDecimal idWeek) {
		this.idWeek = idWeek;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KpiLastDayWeek))
			return false;
		KpiLastDayWeek castOther = (KpiLastDayWeek) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCurrentDay() == castOther.getCurrentDay()) || (this
						.getCurrentDay() != null
						&& castOther.getCurrentDay() != null && this
						.getCurrentDay().equals(castOther.getCurrentDay())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getScheduledOrders() == castOther
						.getScheduledOrders()) || (this.getScheduledOrders() != null
						&& castOther.getScheduledOrders() != null && this
						.getScheduledOrders().equals(
								castOther.getScheduledOrders())))
				&& ((this.getFinishedOrders() == castOther.getFinishedOrders()) || (this
						.getFinishedOrders() != null
						&& castOther.getFinishedOrders() != null && this
						.getFinishedOrders().equals(
								castOther.getFinishedOrders())))
				&& ((this.getFailuresOrders() == castOther.getFailuresOrders()) || (this
						.getFailuresOrders() != null
						&& castOther.getFailuresOrders() != null && this
						.getFailuresOrders().equals(
								castOther.getFailuresOrders())))
				&& ((this.getIdWeek() == castOther.getIdWeek()) || (this
						.getIdWeek() != null && castOther.getIdWeek() != null && this
						.getIdWeek().equals(castOther.getIdWeek())))
				&& (this.getState() == castOther.getState());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getCurrentDay() == null ? 0 : this.getCurrentDay()
						.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37
				* result
				+ (getScheduledOrders() == null ? 0 : this.getScheduledOrders()
						.hashCode());
		result = 37
				* result
				+ (getFinishedOrders() == null ? 0 : this.getFinishedOrders()
						.hashCode());
		result = 37
				* result
				+ (getFailuresOrders() == null ? 0 : this.getFailuresOrders()
						.hashCode());
		result = 37 * result
				+ (getIdWeek() == null ? 0 : this.getIdWeek().hashCode());
		result = 37 * result + this.getState();
		return result;
	}

}
