package co.com.tactusoft.kpi.model.entities;

// Generated 26/04/2012 09:35:42 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import org.hibernate.annotations.NamedNativeQueries;
import org.hibernate.annotations.NamedNativeQuery;

/**
 * KpiDailyDelayWo generated by hbm2java
 */
@Entity
@NamedNativeQueries({ @NamedNativeQuery(name = "callKpiRtDailyDelayWo", query = "CALL kpi_db.kpi_rt_daily_delay_wo(:P_ID_DAILY_DELAY, :P_WO, :P_NUM_HOURS)", resultClass = KpiRtDailyDelayWo.class) })
public class KpiRtDailyDelayWo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idDailyDelay;
	private String wo;
	private BigDecimal numHours;

	public KpiRtDailyDelayWo() {
	}

	public KpiRtDailyDelayWo(BigDecimal id, BigDecimal idDailyDelay, String wo,
			BigDecimal numHours) {
		this.id = id;
		this.idDailyDelay = idDailyDelay;
		this.wo = wo;
		this.numHours = numHours;
	}

	@Id
	@Column(name = "id")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_daily_delay")
	public BigDecimal getIdDailyDelay() {
		return this.idDailyDelay;
	}

	public void setIdDailyDelay(BigDecimal idDailyDelay) {
		this.idDailyDelay = idDailyDelay;
	}

	@Column(name = "wo", length = 45)
	public String getWo() {
		return this.wo;
	}

	public void setWo(String wo) {
		this.wo = wo;
	}

	@Column(name = "num_hours", nullable = false)
	public BigDecimal getNumHours() {
		return this.numHours;
	}

	public void setNumHours(BigDecimal numHours) {
		this.numHours = numHours;
	}

}
