package co.com.tactusoft.kpi.model.entities;

// Generated 27/02/2012 10:57:07 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KpiRole generated by hbm2java
 */
@Entity
@Table(name = "kpi_role", catalog = "kpi_db")
public class KpiRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private int state;
	private Set<KpiUserRole> kpiUserRoles = new HashSet<KpiUserRole>(0);

	public KpiRole() {
	}

	public KpiRole(BigDecimal id, String name, int state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public KpiRole(BigDecimal id, String name, int state,
			Set<KpiUserRole> kpiUserRoles) {
		this.id = id;
		this.name = name;
		this.state = state;
		this.kpiUserRoles = kpiUserRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiRole")
	public Set<KpiUserRole> getKpiUserRoles() {
		return this.kpiUserRoles;
	}

	public void setKpiUserRoles(Set<KpiUserRole> kpiUserRoles) {
		this.kpiUserRoles = kpiUserRoles;
	}

}
