package co.com.tactusoft.kpi.model.entities;

// Generated 27/02/2012 10:57:07 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KpiUser generated by hbm2java
 */
@Entity
@Table(name = "kpi_user", catalog = "kpi_db")
public class KpiUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String username;
	private String password;
	private String firstName;
	private String middleName;
	private String lastName;
	private String phone;
	private KpiCompany kpiCompany;
	private Set<KpiUserRole> kpiUserRoles = new HashSet<KpiUserRole>(0);

	public KpiUser() {
	}

	public KpiUser(BigDecimal id, String username, String firstName,
			String lastName, KpiCompany kpiCompany) {
		this.id = id;
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.kpiCompany = kpiCompany;
	}

	public KpiUser(BigDecimal id, String username, String firstName,
			String middleName, String lastName, String phone,
			KpiCompany kpiCompany, Set<KpiUserRole> kpiUserRoles) {
		this.id = id;
		this.username = username;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.phone = phone;
		this.kpiCompany = kpiCompany;
		this.kpiUserRoles = kpiUserRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_company", nullable = false)
	public KpiCompany getKpiCompany() {
		return kpiCompany;
	}

	public void setKpiCompany(KpiCompany kpiCompany) {
		this.kpiCompany = kpiCompany;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiUser")
	public Set<KpiUserRole> getKpiUserRoles() {
		return this.kpiUserRoles;
	}

	public void setKpiUserRoles(Set<KpiUserRole> kpiUserRoles) {
		this.kpiUserRoles = kpiUserRoles;
	}

}
