package co.com.tactusoft.video.model.entities;

// Generated 5/04/2012 10:49:28 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "medical_video_db")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private Role role;
	private String username;
	private String password;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String phone;
	private int state;
	private Set<VidUserTopic> vidUserTopics = new HashSet<VidUserTopic>(0);
	private Set<VidUserPackage> vidUserPackages = new HashSet<VidUserPackage>(0);

	public User() {
	}

	public User(BigDecimal id, Role role, String username, String password,
			String firstName, String lastName, int state) {
		this.id = id;
		this.role = role;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.state = state;
	}

	public User(BigDecimal id, Role role, String username, String password,
			String firstName, String middleName, String lastName, String email,
			String phone, int state, Set<VidUserTopic> vidUserTopics,
			Set<VidUserPackage> vidUserPackages) {
		this.id = id;
		this.role = role;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.state = state;
		this.vidUserTopics = vidUserTopics;
		this.vidUserPackages = vidUserPackages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 1000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<VidUserTopic> getVidUserTopics() {
		return this.vidUserTopics;
	}

	public void setVidUserTopics(Set<VidUserTopic> vidUserTopics) {
		this.vidUserTopics = vidUserTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<VidUserPackage> getVidUserPackages() {
		return this.vidUserPackages;
	}

	public void setVidUserPackages(Set<VidUserPackage> vidUserPackages) {
		this.vidUserPackages = vidUserPackages;
	}

}
