package co.com.tactusoft.video.model.entities;

// Generated 5/04/2012 12:13:50 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VidPackageTopic generated by hbm2java
 */
@Entity
@Table(name = "vid_package_topic", catalog = "medical_video_db")
public class VidPackageTopic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private VidPackage vidPackage;
	private VidTopic vidTopic;

	public VidPackageTopic() {
	}

	public VidPackageTopic(BigDecimal id, VidPackage vidPackage,
			VidTopic vidTopic) {
		this.id = id;
		this.vidPackage = vidPackage;
		this.vidTopic = vidTopic;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_package", nullable = false)
	public VidPackage getVidPackage() {
		return this.vidPackage;
	}

	public void setVidPackage(VidPackage vidPackage) {
		this.vidPackage = vidPackage;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_topic", nullable = false)
	public VidTopic getVidTopic() {
		return this.vidTopic;
	}

	public void setVidTopic(VidTopic vidTopic) {
		this.vidTopic = vidTopic;
	}

}
