package co.com.tactusoft.video.model.entities;

// Generated 5/04/2012 12:13:50 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VidPackage generated by hbm2java
 */
@Entity
@Table(name = "vid_package", catalog = "medical_video_db")
public class VidPackage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private int state;
	private Set<VidPackageTopic> vidPackageTopics = new HashSet<VidPackageTopic>(
			0);
	private Set<VidUserPackage> vidUserPackages = new HashSet<VidUserPackage>(0);

	public VidPackage() {
	}

	public VidPackage(BigDecimal id, String name, int state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public VidPackage(BigDecimal id, String name, int state,
			Set<VidPackageTopic> vidPackageTopics,
			Set<VidUserPackage> vidUserPackages) {
		this.id = id;
		this.name = name;
		this.state = state;
		this.vidPackageTopics = vidPackageTopics;
		this.vidUserPackages = vidUserPackages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidPackage")
	public Set<VidPackageTopic> getVidPackageTopics() {
		return this.vidPackageTopics;
	}

	public void setVidPackageTopics(Set<VidPackageTopic> vidPackageTopics) {
		this.vidPackageTopics = vidPackageTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidPackage")
	public Set<VidUserPackage> getVidUserPackages() {
		return this.vidUserPackages;
	}

	public void setVidUserPackages(Set<VidUserPackage> vidUserPackages) {
		this.vidUserPackages = vidUserPackages;
	}

}
