package co.com.tactusoft.video.model.entities;

// Generated 3/04/2012 09:31:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VidQuestion generated by hbm2java
 */
@Entity
@Table(name = "vid_question", catalog = "medical_video_db")
public class VidQuestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private VidTopic vidTopic;
	private String name;
	private String typeQuestion;
	private String resourceType;
	private String typeVideo;
	private BigDecimal positive;
	private BigDecimal negative;
	private Integer orderQuestion;
	private Set<VidAnswer> vidAnswers = new HashSet<VidAnswer>(0);

	public VidQuestion() {
	}

	public VidQuestion(BigDecimal id, VidTopic vidTopic, String name,
			String typeQuestion) {
		this.id = id;
		this.vidTopic = vidTopic;
		this.name = name;
		this.typeQuestion = typeQuestion;
	}

	public VidQuestion(BigDecimal id, VidTopic vidTopic, String name,
			String typeQuestion, String resourceType, String typeVideo,
			BigDecimal positive, BigDecimal negative, Integer orderQuestion,
			Set<VidAnswer> vidAnswers) {
		this.id = id;
		this.vidTopic = vidTopic;
		this.name = name;
		this.typeQuestion = typeQuestion;
		this.resourceType = resourceType;
		this.typeVideo = typeVideo;
		this.positive = positive;
		this.negative = negative;
		this.orderQuestion = orderQuestion;
		this.vidAnswers = vidAnswers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_topic", nullable = false)
	public VidTopic getVidTopic() {
		return this.vidTopic;
	}

	public void setVidTopic(VidTopic vidTopic) {
		this.vidTopic = vidTopic;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type_question", nullable = false, length = 45)
	public String getTypeQuestion() {
		return this.typeQuestion;
	}

	public void setTypeQuestion(String typeQuestion) {
		this.typeQuestion = typeQuestion;
	}

	@Column(name = "resource_type", length = 15)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "type_video", length = 45)
	public String getTypeVideo() {
		return this.typeVideo;
	}

	public void setTypeVideo(String typeVideo) {
		this.typeVideo = typeVideo;
	}

	@Column(name = "positive", scale = 0)
	public BigDecimal getPositive() {
		return this.positive;
	}

	public void setPositive(BigDecimal positive) {
		this.positive = positive;
	}

	@Column(name = "negative", scale = 0)
	public BigDecimal getNegative() {
		return this.negative;
	}

	public void setNegative(BigDecimal negative) {
		this.negative = negative;
	}

	@Column(name = "order_question")
	public Integer getOrderQuestion() {
		return this.orderQuestion;
	}

	public void setOrderQuestion(Integer orderQuestion) {
		this.orderQuestion = orderQuestion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidQuestion")
	public Set<VidAnswer> getVidAnswers() {
		return this.vidAnswers;
	}

	public void setVidAnswers(Set<VidAnswer> vidAnswers) {
		this.vidAnswers = vidAnswers;
	}

}
