package co.com.tactusoft.video.model.entities;

// Generated 7/03/2012 10:49:44 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * vidTopic generated by hbm2java
 */
@Entity
@Table(name = "vid_topic", catalog = "medical_video_db")
public class VidTopic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private String image;
	private String gender;
	private int state;
	private Set<VidQuestion> vidQuestions = new HashSet<VidQuestion>(0);

	public VidTopic() {
	}

	public VidTopic(BigDecimal id, String name, int state) {
		this.id = id;
		this.name = name;
		this.state = state;
	}

	public VidTopic(BigDecimal id, String name, String image, String gender,
			int state, Set<VidQuestion> vidQuestions) {
		this.id = id;
		this.name = name;
		this.image = image;
		this.gender = gender;
		this.state = state;
		this.vidQuestions = vidQuestions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "gender", nullable = false)
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vidTopic", cascade = { CascadeType.REMOVE })
	public Set<VidQuestion> getVidQuestions() {
		return this.vidQuestions;
	}

	public void setVidQuestions(Set<VidQuestion> vidQuestions) {
		this.vidQuestions = vidQuestions;
	}

}
