package co.com.tactusoft.crm.model.entities;

// Generated 31/05/2012 07:18:11 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.OrderBy;

/**
 * CrmCountry generated by hbm2java
 */
@Entity
@Table(name = "crm_country", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmCountry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String code;
	private String name;
	private Set<CrmRegion> crmRegions = new HashSet<CrmRegion>(0);

	public CrmCountry() {
	}

	public CrmCountry(BigDecimal id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public CrmCountry(BigDecimal id, String code, String name,
			Set<CrmRegion> crmRegions) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.crmRegions = crmRegions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OrderBy(clause = "name")
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "crmCountry")
	public Set<CrmRegion> getCrmRegions() {
		return this.crmRegions;
	}

	public void setCrmRegions(Set<CrmRegion> crmRegions) {
		this.crmRegions = crmRegions;
	}

}
