package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmCampaign generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign", catalog = "crm_db")
public class CrmCampaign implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idPatient;
	private BigDecimal idUser;
	private BigDecimal idBranch;
	private String observation;
	private Integer state;
	private Set<CrmCampaignDetail> crmCampaignDetails = new HashSet<CrmCampaignDetail>(
			0);

	public CrmCampaign() {
	}

	public CrmCampaign(BigDecimal id, BigDecimal idPatient, BigDecimal idUser,
			BigDecimal idBranch) {
		this.id = id;
		this.idPatient = idPatient;
		this.idUser = idUser;
		this.idBranch = idBranch;
	}

	public CrmCampaign(BigDecimal id, BigDecimal idPatient, BigDecimal idUser,
			BigDecimal idBranch, String observation,
			Set<CrmCampaignDetail> crmCampaignDetails) {
		this.id = id;
		this.idPatient = idPatient;
		this.idUser = idUser;
		this.idBranch = idBranch;
		this.observation = observation;
		this.crmCampaignDetails = crmCampaignDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_patient", nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "id_user", nullable = false, scale = 0)
	public BigDecimal getIdUser() {
		return this.idUser;
	}

	public void setIdUser(BigDecimal idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_branch", nullable = false, scale = 0)
	public BigDecimal getIdBranch() {
		return idBranch;
	}

	public void setIdBranch(BigDecimal idBranch) {
		this.idBranch = idBranch;
	}

	@Column(name = "observation", length = 65535)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "state", nullable = false, scale = 0)
	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmCampaign")
	public Set<CrmCampaignDetail> getCrmCampaignDetails() {
		return this.crmCampaignDetails;
	}

	public void setCrmCampaignDetails(Set<CrmCampaignDetail> crmCampaignDetails) {
		this.crmCampaignDetails = crmCampaignDetails;
	}

}
