package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmDoctor generated by hbm2java
 */
@Entity
@Table(name = "crm_doctor", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class CrmDoctor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmSpeciality crmSpeciality;
	private CrmBranch crmBranch;
	private String code;
	private String firstName;
	private String secondName;
	private String firstSurname;
	private String secondSurname;
	private String gender;
	private Boolean onSite;
	private Boolean virtual;
	private int state;
	private Set<CrmAppointment> crmAppointments = new HashSet<CrmAppointment>(0);
	private Set<CrmDoctorSchedule> crmDoctorSchedules = new HashSet<CrmDoctorSchedule>(
			0);
	private Set<CrmDoctorException> crmDoctorExceptions = new HashSet<CrmDoctorException>(
			0);

	public CrmDoctor() {
	}

	public CrmDoctor(BigDecimal id, CrmSpeciality crmSpeciality,
			CrmBranch crmBranch, String code, String firstName,
			String firstSurname, int state) {
		this.id = id;
		this.crmSpeciality = crmSpeciality;
		this.crmBranch = crmBranch;
		this.code = code;
		this.firstName = firstName;
		this.firstSurname = firstSurname;
		this.state = state;
	}

	public CrmDoctor(BigDecimal id, CrmSpeciality crmSpeciality,
			CrmBranch crmBranch, String code, String firstName,
			String secondName, String firstSurname, String secondSurname,
			String gender, Boolean onSite, Boolean virtual, int state,
			Set<CrmAppointment> crmAppointments,
			Set<CrmDoctorSchedule> crmDoctorSchedules,
			Set<CrmDoctorException> crmDoctorExceptions) {
		this.id = id;
		this.crmSpeciality = crmSpeciality;
		this.crmBranch = crmBranch;
		this.code = code;
		this.firstName = firstName;
		this.secondName = secondName;
		this.firstSurname = firstSurname;
		this.secondSurname = secondSurname;
		this.gender = gender;
		this.onSite = onSite;
		this.virtual = virtual;
		this.state = state;
		this.crmAppointments = crmAppointments;
		this.crmDoctorSchedules = crmDoctorSchedules;
		this.crmDoctorExceptions = crmDoctorExceptions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_speciality", nullable = false)
	public CrmSpeciality getCrmSpeciality() {
		return this.crmSpeciality;
	}

	public void setCrmSpeciality(CrmSpeciality crmSpeciality) {
		this.crmSpeciality = crmSpeciality;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_branch", nullable = false)
	public CrmBranch getCrmBranch() {
		return this.crmBranch;
	}

	public void setCrmBranch(CrmBranch crmBranch) {
		this.crmBranch = crmBranch;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "second_name", length = 45)
	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	@Column(name = "first_surname", nullable = false, length = 45)
	public String getFirstSurname() {
		return this.firstSurname;
	}

	public void setFirstSurname(String firstSurname) {
		this.firstSurname = firstSurname;
	}

	@Column(name = "second_surname", length = 45)
	public String getSecondSurname() {
		return this.secondSurname;
	}

	public void setSecondSurname(String secondSurname) {
		this.secondSurname = secondSurname;
	}

	@Column(name = "gender", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "on_site")
	public Boolean getOnSite() {
		return this.onSite;
	}

	public void setOnSite(Boolean onSite) {
		this.onSite = onSite;
	}

	@Column(name = "virtual")
	public Boolean getVirtual() {
		return this.virtual;
	}

	public void setVirtual(Boolean virtual) {
		this.virtual = virtual;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmDoctor")
	public Set<CrmAppointment> getCrmAppointments() {
		return this.crmAppointments;
	}

	public void setCrmAppointments(Set<CrmAppointment> crmAppointments) {
		this.crmAppointments = crmAppointments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmDoctor")
	public Set<CrmDoctorSchedule> getCrmDoctorSchedules() {
		return this.crmDoctorSchedules;
	}

	public void setCrmDoctorSchedules(Set<CrmDoctorSchedule> crmDoctorSchedules) {
		this.crmDoctorSchedules = crmDoctorSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmDoctor")
	public Set<CrmDoctorException> getCrmDoctorExceptions() {
		return this.crmDoctorExceptions;
	}

	public void setCrmDoctorExceptions(
			Set<CrmDoctorException> crmDoctorExceptions) {
		this.crmDoctorExceptions = crmDoctorExceptions;
	}

}
