package co.com.tactusoft.crm.model.entities;

// Generated 20/06/2012 02:16:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmHistoryHistory generated by hbm2java
 */
@Entity
@Table(name = "crm_history_history", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "id_patient"))
public class CrmHistoryHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idPatient;
	private String reason;
	private String disease;
	private String head;
	private String orl;
	private String cr;
	private String gi;
	private String neuromuscular;
	private String gu;
	private String psychiatric;
	private String skin;

	public CrmHistoryHistory() {
	}

	public CrmHistoryHistory(BigDecimal id, BigDecimal idPatient) {
		this.id = id;
		this.idPatient = idPatient;
	}

	public CrmHistoryHistory(BigDecimal id, BigDecimal idPatient,
			String reason, String disease, String head, String orl, String cr,
			String gi, String neuromuscular, String gu, String psychiatric,
			String skin) {
		this.id = id;
		this.idPatient = idPatient;
		this.reason = reason;
		this.disease = disease;
		this.head = head;
		this.orl = orl;
		this.cr = cr;
		this.gi = gi;
		this.neuromuscular = neuromuscular;
		this.gu = gu;
		this.psychiatric = psychiatric;
		this.skin = skin;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_patient", unique = true, nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "reason", length = 1000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "disease", length = 1000)
	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	@Column(name = "head", length = 1)
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "orl", length = 1)
	public String getOrl() {
		return this.orl;
	}

	public void setOrl(String orl) {
		this.orl = orl;
	}

	@Column(name = "cr", length = 1)
	public String getCr() {
		return this.cr;
	}

	public void setCr(String cr) {
		this.cr = cr;
	}

	@Column(name = "gi", length = 1)
	public String getGi() {
		return this.gi;
	}

	public void setGi(String gi) {
		this.gi = gi;
	}

	@Column(name = "neuromuscular", length = 1)
	public String getNeuromuscular() {
		return this.neuromuscular;
	}

	public void setNeuromuscular(String neuromuscular) {
		this.neuromuscular = neuromuscular;
	}

	@Column(name = "gu", length = 1)
	public String getGu() {
		return this.gu;
	}

	public void setGu(String gu) {
		this.gu = gu;
	}

	@Column(name = "psychiatric", length = 1)
	public String getPsychiatric() {
		return this.psychiatric;
	}

	public void setPsychiatric(String psychiatric) {
		this.psychiatric = psychiatric;
	}

	@Column(name = "skin", length = 1)
	public String getSkin() {
		return this.skin;
	}

	public void setSkin(String skin) {
		this.skin = skin;
	}

}
