package co.com.tactusoft.crm.model.entities;

// Generated 20/06/2012 02:16:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmHistoryRecord generated by hbm2java
 */
@Entity
@Table(name = "crm_history_record", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "id_patient"))
public class CrmHistoryRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private BigDecimal idPatient;
	private Boolean hypertension;
	private Boolean heart;
	private Boolean cancer;
	private Boolean arthritis;
	private Boolean diabetes;
	private String diabetesTime;
	private String diabetesGlycemia;
	private String others;
	private String surgicalDesc;
	private String pharmacologicalDesc;
	private String toxicDesc;
	private String transfusionDesc;
	private String allergyDesc;
	private String immunizationsDesc;
	private String othersRecors;
	private String familyHistory;
	private String gestation;
	private String obstGynP;
	private String obstGynA;
	private String obstGynC;
	private String obstGynFur;
	private String obstGynOthers;

	public CrmHistoryRecord() {
	}

	public CrmHistoryRecord(BigDecimal id, BigDecimal idPatient) {
		this.id = id;
		this.idPatient = idPatient;
	}

	public CrmHistoryRecord(BigDecimal id, BigDecimal idPatient,
			Boolean hypertension, Boolean heart, Boolean cancer,
			Boolean arthritis, Boolean diabetes, String diabetesTime,
			String diabetesGlycemia, String others, String surgicalDesc,
			String pharmacologicalDesc, String toxicDesc,
			String transfusionDesc, String allergyDesc,
			String immunizationsDesc, String othersRecors,
			String familyHistory, String gestation, String obstGynP,
			String obstGynA, String obstGynC, String obstGynFur,
			String obstGynOthers) {
		this.id = id;
		this.idPatient = idPatient;
		this.hypertension = hypertension;
		this.heart = heart;
		this.cancer = cancer;
		this.arthritis = arthritis;
		this.diabetes = diabetes;
		this.diabetesTime = diabetesTime;
		this.diabetesGlycemia = diabetesGlycemia;
		this.others = others;
		this.surgicalDesc = surgicalDesc;
		this.pharmacologicalDesc = pharmacologicalDesc;
		this.toxicDesc = toxicDesc;
		this.transfusionDesc = transfusionDesc;
		this.allergyDesc = allergyDesc;
		this.immunizationsDesc = immunizationsDesc;
		this.othersRecors = othersRecors;
		this.familyHistory = familyHistory;
		this.gestation = gestation;
		this.obstGynP = obstGynP;
		this.obstGynA = obstGynA;
		this.obstGynC = obstGynC;
		this.obstGynFur = obstGynFur;
		this.obstGynOthers = obstGynOthers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "id_patient", unique = true, nullable = false, scale = 0)
	public BigDecimal getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(BigDecimal idPatient) {
		this.idPatient = idPatient;
	}

	@Column(name = "hypertension")
	public Boolean getHypertension() {
		return this.hypertension;
	}

	public void setHypertension(Boolean hypertension) {
		this.hypertension = hypertension;
	}

	@Column(name = "heart")
	public Boolean getHeart() {
		return this.heart;
	}

	public void setHeart(Boolean heart) {
		this.heart = heart;
	}

	@Column(name = "cancer")
	public Boolean getCancer() {
		return this.cancer;
	}

	public void setCancer(Boolean cancer) {
		this.cancer = cancer;
	}

	@Column(name = "arthritis")
	public Boolean getArthritis() {
		return this.arthritis;
	}

	public void setArthritis(Boolean arthritis) {
		this.arthritis = arthritis;
	}

	@Column(name = "diabetes")
	public Boolean getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(Boolean diabetes) {
		this.diabetes = diabetes;
	}

	@Column(name = "diabetes_time", length = 45)
	public String getDiabetesTime() {
		return this.diabetesTime;
	}

	public void setDiabetesTime(String diabetesTime) {
		this.diabetesTime = diabetesTime;
	}

	@Column(name = "diabetes_glycemia", length = 45)
	public String getDiabetesGlycemia() {
		return this.diabetesGlycemia;
	}

	public void setDiabetesGlycemia(String diabetesGlycemia) {
		this.diabetesGlycemia = diabetesGlycemia;
	}

	@Column(name = "others", length = 1000)
	public String getOthers() {
		return this.others;
	}

	public void setOthers(String others) {
		this.others = others;
	}

	@Column(name = "surgical_desc", length = 1000)
	public String getSurgicalDesc() {
		return this.surgicalDesc;
	}

	public void setSurgicalDesc(String surgicalDesc) {
		this.surgicalDesc = surgicalDesc;
	}

	@Column(name = "pharmacological_desc", length = 1000)
	public String getPharmacologicalDesc() {
		return this.pharmacologicalDesc;
	}

	public void setPharmacologicalDesc(String pharmacologicalDesc) {
		this.pharmacologicalDesc = pharmacologicalDesc;
	}

	@Column(name = "toxic_desc", length = 1000)
	public String getToxicDesc() {
		return this.toxicDesc;
	}

	public void setToxicDesc(String toxicDesc) {
		this.toxicDesc = toxicDesc;
	}

	@Column(name = "transfusion_desc", length = 1000)
	public String getTransfusionDesc() {
		return this.transfusionDesc;
	}

	public void setTransfusionDesc(String transfusionDesc) {
		this.transfusionDesc = transfusionDesc;
	}

	@Column(name = "allergy_desc", length = 1000)
	public String getAllergyDesc() {
		return this.allergyDesc;
	}

	public void setAllergyDesc(String allergyDesc) {
		this.allergyDesc = allergyDesc;
	}

	@Column(name = "immunizations_desc", length = 1000)
	public String getImmunizationsDesc() {
		return this.immunizationsDesc;
	}

	public void setImmunizationsDesc(String immunizationsDesc) {
		this.immunizationsDesc = immunizationsDesc;
	}

	@Column(name = "others_recors", length = 1000)
	public String getOthersRecors() {
		return this.othersRecors;
	}

	public void setOthersRecors(String othersRecors) {
		this.othersRecors = othersRecors;
	}

	@Column(name = "family_history", length = 1000)
	public String getFamilyHistory() {
		return this.familyHistory;
	}

	public void setFamilyHistory(String familyHistory) {
		this.familyHistory = familyHistory;
	}

	@Column(name = "gestation", length = 45)
	public String getGestation() {
		return this.gestation;
	}

	public void setGestation(String gestation) {
		this.gestation = gestation;
	}

	@Column(name = "obst_gyn_p", length = 45)
	public String getObstGynP() {
		return this.obstGynP;
	}

	public void setObstGynP(String obstGynP) {
		this.obstGynP = obstGynP;
	}

	@Column(name = "obst_gyn_a", length = 45)
	public String getObstGynA() {
		return this.obstGynA;
	}

	public void setObstGynA(String obstGynA) {
		this.obstGynA = obstGynA;
	}

	@Column(name = "obst_gyn_c", length = 45)
	public String getObstGynC() {
		return this.obstGynC;
	}

	public void setObstGynC(String obstGynC) {
		this.obstGynC = obstGynC;
	}

	@Column(name = "obst_gyn_fur", length = 45)
	public String getObstGynFur() {
		return this.obstGynFur;
	}

	public void setObstGynFur(String obstGynFur) {
		this.obstGynFur = obstGynFur;
	}

	@Column(name = "obst_gyn_others", length = 1000)
	public String getObstGynOthers() {
		return this.obstGynOthers;
	}

	public void setObstGynOthers(String obstGynOthers) {
		this.obstGynOthers = obstGynOthers;
	}

}
