package co.com.tactusoft.crm.model.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CrmOtherMedication generated by hbm2java
 */
@Entity
@Table(name = "crm_other_medication", catalog = "crm_db")
public class CrmOtherMedication implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private CrmAppointment crmAppointment;
	private String medication;
	private String posology;
	private String diagnosis;
	
	private int sequence;

	public CrmOtherMedication() {
	}

	public CrmOtherMedication(CrmAppointment crmAppointment, String medication,
			String posology, String diagnosis) {
		this.crmAppointment = crmAppointment;
		this.medication = medication;
		this.posology = posology;
		this.diagnosis = diagnosis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_appointment", nullable = false)
	public CrmAppointment getCrmAppointment() {
		return crmAppointment;
	}

	public void setCrmAppointment(CrmAppointment crmAppointment) {
		this.crmAppointment = crmAppointment;
	}

	@Column(name = "medication", nullable = false, length = 65535)
	public String getMedication() {
		return this.medication;
	}

	public void setMedication(String medication) {
		this.medication = medication;
	}

	@Column(name = "posology", nullable = false, length = 65535)
	public String getPosology() {
		return this.posology;
	}

	public void setPosology(String posology) {
		this.posology = posology;
	}

	@Column(name = "diagnosis", nullable = false, length = 65535)
	public String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(String diagnosis) {
		this.diagnosis = diagnosis;
	}

	@Transient
	public int getSequence() {
		return sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

}
