package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmProcedureDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_procedure_detail", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class CrmProcedureDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmProcedure crmProcedure;
	private String name;
	private Integer timeDoctor;
	private Integer timeNurses;
	private Integer timeStretchers;
	private int state;

	public CrmProcedureDetail() {
	}

	public CrmProcedureDetail(BigDecimal id, CrmProcedure crmProcedure,
			String name, int state) {
		this.id = id;
		this.crmProcedure = crmProcedure;
		this.name = name;
		this.state = state;
	}

	public CrmProcedureDetail(BigDecimal id, CrmProcedure crmProcedure,
			String name, Integer timeDoctor, Integer timeNurses,
			Integer timeStretchers, int state) {
		this.id = id;
		this.crmProcedure = crmProcedure;
		this.name = name;
		this.timeDoctor = timeDoctor;
		this.timeNurses = timeNurses;
		this.timeStretchers = timeStretchers;
		this.state = state;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_procedure", nullable = false)
	public CrmProcedure getCrmProcedure() {
		return this.crmProcedure;
	}

	public void setCrmProcedure(CrmProcedure crmProcedure) {
		this.crmProcedure = crmProcedure;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "time_doctor")
	public Integer getTimeDoctor() {
		return this.timeDoctor;
	}

	public void setTimeDoctor(Integer timeDoctor) {
		this.timeDoctor = timeDoctor;
	}

	@Column(name = "time_nurses")
	public Integer getTimeNurses() {
		return this.timeNurses;
	}

	public void setTimeNurses(Integer timeNurses) {
		this.timeNurses = timeNurses;
	}

	@Column(name = "time_stretchers")
	public Integer getTimeStretchers() {
		return this.timeStretchers;
	}

	public void setTimeStretchers(Integer timeStretchers) {
		this.timeStretchers = timeStretchers;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
