package co.com.tactusoft.crm.model.entities;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CrmUser generated by hbm2java
 */
@Entity
@Table(name = "crm_user", catalog = "crm_db", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class CrmUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmDepartment crmDepartment;
	private CrmProfile crmProfile;
	private String username;
	private String password;
	private String firstName;
	private String middleName;
	private String firstSurname;
	private String secondSurname;
	private String email;
	private String phone;
	private String extension;
	private int state;
	private Set<CrmUserBranch> crmUserBranchs = new HashSet<CrmUserBranch>(0);
	private Set<CrmUserRole> crmUserRoles = new HashSet<CrmUserRole>(0);

	public CrmUser() {
	}

	public CrmUser(BigDecimal id, CrmDepartment crmDepartment,
			CrmProfile crmProfile, String username, String password,
			String firstName, String firstSurname, String email, int state) {
		this.id = id;
		this.crmDepartment = crmDepartment;
		this.crmProfile = crmProfile;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.firstSurname = firstSurname;
		this.email = email;
		this.state = state;
	}

	public CrmUser(BigDecimal id, CrmDepartment crmDepartment,
			CrmProfile crmProfile, String username, String password,
			String firstName, String middleName, String firstSurname,
			String secondSurname, String email, String phone, String extension,
			int state, Set<CrmUserBranch> crmUserBranchs,
			Set<CrmUserRole> crmUserRoles) {
		this.id = id;
		this.crmDepartment = crmDepartment;
		this.crmProfile = crmProfile;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.middleName = middleName;
		this.firstSurname = firstSurname;
		this.secondSurname = secondSurname;
		this.email = email;
		this.phone = phone;
		this.extension = extension;
		this.state = state;
		this.crmUserBranchs = crmUserBranchs;
		this.crmUserRoles = crmUserRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_departament", nullable = false)
	public CrmDepartment getCrmDepartment() {
		return this.crmDepartment;
	}

	public void setCrmDepartment(CrmDepartment crmDepartment) {
		this.crmDepartment = crmDepartment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_profile", nullable = false)
	public CrmProfile getCrmProfile() {
		return this.crmProfile;
	}

	public void setCrmProfile(CrmProfile crmProfile) {
		this.crmProfile = crmProfile;
	}

	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "first_surname", nullable = false)
	public String getFirstSurname() {
		return this.firstSurname;
	}

	public void setFirstSurname(String firstSurname) {
		this.firstSurname = firstSurname;
	}

	@Column(name = "second_surname")
	public String getSecondSurname() {
		return this.secondSurname;
	}

	public void setSecondSurname(String secondSurname) {
		this.secondSurname = secondSurname;
	}

	@Column(name = "email", nullable = false, length = 1000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "extension")
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmUser")
	public Set<CrmUserBranch> getCrmUserBranchs() {
		return this.crmUserBranchs;
	}

	public void setCrmUserBranchs(Set<CrmUserBranch> crmUserBranchs) {
		this.crmUserBranchs = crmUserBranchs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmUser")
	public Set<CrmUserRole> getCrmUserRoles() {
		return this.crmUserRoles;
	}

	public void setCrmUserRoles(Set<CrmUserRole> crmUserRoles) {
		this.crmUserRoles = crmUserRoles;
	}

}
