package co.com.tactusoft.sap.entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrmCampaignDetail generated by hbm2java
 */
@Entity
@Table(name = "crm_campaign_detail", catalog = "crm_db")
public class CrmCampaignDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private CrmCampaign crmCampaign;
	private String codMaterial;
	private String descMaterial;

	public CrmCampaignDetail() {
	}

	public CrmCampaignDetail(BigDecimal id, CrmCampaign crmCampaign,
			String codMaterial, String descMaterial) {
		this.id = id;
		this.crmCampaign = crmCampaign;
		this.codMaterial = codMaterial;
		this.descMaterial = descMaterial;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_campaign", nullable = false)
	public CrmCampaign getCrmCampaign() {
		return this.crmCampaign;
	}

	public void setCrmCampaign(CrmCampaign crmCampaign) {
		this.crmCampaign = crmCampaign;
	}

	@Column(name = "cod_material", nullable = false, length = 18)
	public String getCodMaterial() {
		return this.codMaterial;
	}

	public void setCodMaterial(String codMaterial) {
		this.codMaterial = codMaterial;
	}

	@Column(name = "desc_material", nullable = false, length = 1000)
	public String getDescMaterial() {
		return this.descMaterial;
	}

	public void setDescMaterial(String descMaterial) {
		this.descMaterial = descMaterial;
	}

}
