package co.com.tactusoft.kpi.model.entities;

// Generated 20/02/2012 11:10:42 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KpiDaily generated by hbm2java
 */
@Entity
@Table(name = "kpi_daily", catalog = "kpi")
public class KpiDaily implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private KpiWeek kpiWeek;
	private Date currentDay;
	private String description;
	private Integer scheduledOrders;
	private Integer finishedOrders;
	private Integer failuresOrders;
	private int state;
	private Set<KpiDailyDelay> kpiDailyDelaies = new HashSet<KpiDailyDelay>(0);

	public KpiDaily() {
	}

	public KpiDaily(BigDecimal id, KpiWeek kpiWeek, Date currentDay, int state) {
		this.id = id;
		this.kpiWeek = kpiWeek;
		this.currentDay = currentDay;
		this.state = state;
	}

	public KpiDaily(BigDecimal id, KpiWeek kpiWeek, Date currentDay,
			String description, Integer scheduledOrders,
			Integer finishedOrders, Integer failuresOrders, int state,
			Set<KpiDailyDelay> kpiDailyDelaies) {
		this.id = id;
		this.kpiWeek = kpiWeek;
		this.currentDay = currentDay;
		this.description = description;
		this.scheduledOrders = scheduledOrders;
		this.finishedOrders = finishedOrders;
		this.failuresOrders = failuresOrders;
		this.state = state;
		this.kpiDailyDelaies = kpiDailyDelaies;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_week", nullable = false)
	public KpiWeek getKpiWeek() {
		return this.kpiWeek;
	}

	public void setKpiWeek(KpiWeek kpiWeek) {
		this.kpiWeek = kpiWeek;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "current_day", nullable = false, length = 19)
	public Date getCurrentDay() {
		return this.currentDay;
	}

	public void setCurrentDay(Date currentDay) {
		this.currentDay = currentDay;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "scheduled_orders")
	public Integer getScheduledOrders() {
		return this.scheduledOrders;
	}

	public void setScheduledOrders(Integer scheduledOrders) {
		this.scheduledOrders = scheduledOrders;
	}

	@Column(name = "finished_orders")
	public Integer getFinishedOrders() {
		return this.finishedOrders;
	}

	public void setFinishedOrders(Integer finishedOrders) {
		this.finishedOrders = finishedOrders;
	}

	@Column(name = "failures_orders")
	public Integer getFailuresOrders() {
		return this.failuresOrders;
	}

	public void setFailuresOrders(Integer failuresOrders) {
		this.failuresOrders = failuresOrders;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiDaily")
	public Set<KpiDailyDelay> getKpiDailyDelaies() {
		return this.kpiDailyDelaies;
	}

	public void setKpiDailyDelaies(Set<KpiDailyDelay> kpiDailyDelaies) {
		this.kpiDailyDelaies = kpiDailyDelaies;
	}

}
