package co.com.tactusoft.kpi.model.entities;

// Generated 26/02/2012 07:44:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KpiData generated by hbm2java
 */
@Entity
@Table(name = "kpi_data", catalog = "kpi_db")
public class KpiData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String name;
	private String unit;
	private String desiredDirection;
	private BigDecimal planAttainment;
	private Byte daily;
	private Byte weekly;
	private Byte monthly;
	private Byte yearly;
	private Integer calculatioType;
	private Set<KpiHeaderData> kpiHeaderDatas = new HashSet<KpiHeaderData>(0);

	public KpiData() {
	}

	public KpiData(BigDecimal id, String name, String unit,
			String desiredDirection, BigDecimal planAttainment) {
		this.id = id;
		this.name = name;
		this.unit = unit;
		this.desiredDirection = desiredDirection;
		this.planAttainment = planAttainment;
	}

	public KpiData(BigDecimal id, String name, String unit,
			String desiredDirection, BigDecimal planAttainment, Byte daily,
			Byte weekly, Byte monthly, Byte yearly,
			Set<KpiHeaderData> kpiHeaderDatas) {
		this.id = id;
		this.name = name;
		this.unit = unit;
		this.desiredDirection = desiredDirection;
		this.planAttainment = planAttainment;
		this.daily = daily;
		this.weekly = weekly;
		this.monthly = monthly;
		this.yearly = yearly;
		this.kpiHeaderDatas = kpiHeaderDatas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "unit", nullable = false, length = 45)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "desired_direction", nullable = false, length = 5)
	public String getDesiredDirection() {
		return this.desiredDirection;
	}

	public void setDesiredDirection(String desiredDirection) {
		this.desiredDirection = desiredDirection;
	}

	@Column(name = "plan_attainment", nullable = false, scale = 3)
	public BigDecimal getPlanAttainment() {
		return this.planAttainment;
	}

	public void setPlanAttainment(BigDecimal planAttainment) {
		this.planAttainment = planAttainment;
	}

	@Column(name = "daily")
	public Byte getDaily() {
		return this.daily;
	}

	public void setDaily(Byte daily) {
		this.daily = daily;
	}

	@Column(name = "weekly")
	public Byte getWeekly() {
		return this.weekly;
	}

	public void setWeekly(Byte weekly) {
		this.weekly = weekly;
	}

	@Column(name = "monthly")
	public Byte getMonthly() {
		return this.monthly;
	}

	public void setMonthly(Byte monthly) {
		this.monthly = monthly;
	}

	@Column(name = "yearly")
	public Byte getYearly() {
		return this.yearly;
	}

	public void setYearly(Byte yearly) {
		this.yearly = yearly;
	}

	@Column(name = "calculation_type")
	public Integer getCalculatioType() {
		return calculatioType;
	}

	public void setCalculatioType(Integer calculatioType) {
		this.calculatioType = calculatioType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kpiData")
	public Set<KpiHeaderData> getKpiHeaderDatas() {
		return this.kpiHeaderDatas;
	}

	public void setKpiHeaderDatas(Set<KpiHeaderData> kpiHeaderDatas) {
		this.kpiHeaderDatas = kpiHeaderDatas;
	}

}
