package co.com.tactusoft.kpi.model.entities;

// Generated 26/04/2012 09:35:42 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * KpiDailyDelayWo generated by hbm2java
 */
@Entity
@Table(name = "kpi_daily_delay_wo", catalog = "kpi_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_daily_delay", "wo" }))
public class KpiDailyDelayWo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private KpiDailyDelay kpiDailyDelay;
	private String wo;
	private BigDecimal numHours;

	public KpiDailyDelayWo() {
	}

	public KpiDailyDelayWo(BigDecimal id, BigDecimal numHours) {
		this.id = id;
		this.numHours = numHours;
	}

	public KpiDailyDelayWo(BigDecimal id, KpiDailyDelay kpiDailyDelay,
			String wo, BigDecimal numHours) {
		this.id = id;
		this.kpiDailyDelay = kpiDailyDelay;
		this.wo = wo;
		this.numHours = numHours;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_daily_delay")
	public KpiDailyDelay getKpiDailyDelay() {
		return this.kpiDailyDelay;
	}

	public void setKpiDailyDelay(KpiDailyDelay kpiDailyDelay) {
		this.kpiDailyDelay = kpiDailyDelay;
	}

	@Column(name = "wo", length = 45)
	public String getWo() {
		return this.wo;
	}

	public void setWo(String wo) {
		this.wo = wo;
	}

	@Column(name = "num_hours", nullable = false)
	public BigDecimal getNumHours() {
		return this.numHours;
	}

	public void setNumHours(BigDecimal numHours) {
		this.numHours = numHours;
	}

}
