package co.com.tactusoft.kpi.model.entities;

// Generated 20/02/2012 11:10:42 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KpiConfig generated by hbm2java
 */
@Entity
@Table(name = "kpi_header_delay", catalog = "kpi")
public class KpiHeaderDelay implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private KpiDelay kpiDelay;
	private KpiHeader kpiHeader;

	public KpiHeaderDelay() {
	}

	public KpiHeaderDelay(BigDecimal id, KpiDelay kpiDelay, KpiHeader kpiHeader) {
		this.id = id;
		this.kpiDelay = kpiDelay;
		this.kpiHeader = kpiHeader;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_delay", nullable = false)
	public KpiDelay getKpiDelay() {
		return this.kpiDelay;
	}

	public void setKpiDelay(KpiDelay kpiDelay) {
		this.kpiDelay = kpiDelay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_header", nullable = false)
	public KpiHeader getKpiHeader() {
		return this.kpiHeader;
	}

	public void setKpiHeader(KpiHeader kpiHeader) {
		this.kpiHeader = kpiHeader;
	}

}
