package co.com.tactusoft.kpi.model.entities;

// Generated 26/02/2012 07:44:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KpiHeaderData generated by hbm2java
 */
@Entity
@Table(name = "kpi_header_data", catalog = "kpi_db")
public class KpiHeaderData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private KpiData kpiData;
	private KpiHeader kpiHeader;
	private Integer korder; 

	public KpiHeaderData() {
	}

	public KpiHeaderData(BigDecimal id, KpiData kpiData, KpiHeader kpiHeader, Integer korder) {
		this.id = id;
		this.kpiData = kpiData;
		this.kpiHeader = kpiHeader;
		this.korder = korder;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_data", nullable = false)
	public KpiData getKpiData() {
		return this.kpiData;
	}

	public void setKpiData(KpiData kpiData) {
		this.kpiData = kpiData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_header", nullable = false)
	public KpiHeader getKpiHeader() {
		return this.kpiHeader;
	}

	public void setKpiHeader(KpiHeader kpiHeader) {
		this.kpiHeader = kpiHeader;
	}
	
	@Column(name = "KORDER")
	public Integer getKorder() {
		return this.korder;
	}

	public void setKorder(Integer korder) {
		this.korder = korder;
	}

}
